### PR TITLE
5 small a11y fixes

### LINKED ISSUE #1125: Console logs: colorization readability
There was some concern brought up during the UX board meeting today about the readability/legibility of some of the text in the console logs when project logs are colorized. Specifically, the default .NET logging "FAIL" display, e.g.:

image

Right now we are using roughly the same display as windows terminal defaults to (campbell color scheme, 12pt font, cascadia mono font) so we should be pretty close to what they'd see in the actual terminal (rendering differences between the browser and the terminal aside). 

There were some suggestions of trying to use a badge like we do for stderr output since that has better padding and whatnot. 

When thinking about this, we need to remember that it is the customer's code that is deciding what to render here. They could do white-text-on-white-background for instance if they wanted. So anything "custom" we try to do to handle scenarios that don't look great should keep that in mind.

### PR DESCRIPTION
**Pull request by adamint**
1. the condition select in filter dialog was missing a label
2. we did not need labels on the divs in source column
3. adds slightly more contrast to the subtext here: (foreground-subtext-rest)

image
image
vs  
image

4. neutral-layer-4 was just _slightly_ too light in light theme and caused contrast issues between the application title (in logo header) and the background. It has been ever so slightly darkened, small enough that you really wouldn't even notice the change

5. fixes insufficient contrast in the red `fail` ansi log by lightening the color. we could eventually turn this into a badge, but it will require re-working the parser (fixes #1125)

This PR fixes all of the current accessibility issues caught by automated checkers.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1380)

### CODE REVIEW

**Comment by tlmii** [comment]
> 4. neutral-layer-4 was just slightly too light in light theme and caused contrast issues between the application title (in logo header) and the background. It has been ever so slightly darkened, small enough that you really wouldn't even notice the change

I'm confused about this one. Are you referring to this?

image


I don't see any contrast issues with that. It needs to be 3:1 and it is more than 4:1 (:

image

(the text is `--accent-fill-rest`, which is `#6734FF`, the background is `--neutral-layer-4`, which is `#D6D6D6` and the font size is `--type-ramp-plus-2-font-size`, which is `20px`)

Though your screenshot seems to say that --neutral-layer-4 is `#6F6F6F` so I'm not sure if I'm looking at the right thing?

**Comment by adamint** [comment]
> I don't see any contrast issues with that. It needs to be 3:1 and it is more than 4:1 (:

18pt is 24.5px, which is larger than the text size, so this does apply!

**Comment by adamint** [comment]
Yes, so sorry! I meant for those images to be associated with #3.

**Comment by tlmii** [comment]
Apologies, you're right. I glossed over the pt vs px distinction in the rule vs how we did sizing. 

That said, I don't think this is the right fix. `--neutral-layer-4` is set by the adaptive color system (recipe) in FAST and we should strive not to change the recipe colors as it can cause us more headaches down the road. Theoretically, all the recipe colors are produced so that all the recipe foregrounds work properly with the recipe backgrounds, etc. If we adjust one of the backgrounds (like `--neutral-layer-4`) we run the risk that one of the foregrounds won't work with it and then we're back in the same spot, likely without realizing it.

The problem here is probably that I used `--accent-fill-rest` for the font color. That's wrong from the color system's perspective because it's a fill color and so foreground/background contrast with another fill color wouldn't be guaranteed. The right thing to use would have been `--accent-foreground-rest` (which is `#1d00d0`) which meets the contrast requirements with `--neutral-layer-4`. Given how close in name `--accent-fill-rest` and `--accent-foreground-rest` are, I'm guessing that was just a typo by me originally

**Comment by tlmii** [comment]
Assuming this

image

Is the header from the details panel on the Trace page (I think that's right), the background is `--neutral-layer-4` so if you don't change that color because of my previous comment, then the change to the font color isn't sufficient anymore. Looks like it'd probably need to go as dark as `#5D5D5D`. Which I think would be fine everywhere else it is used but I'm not certain. Definitely getting a little dark to maintain the visual contrast with the regular text though...

**Comment by tlmii** [comment]
> fixes insufficient contrast in the red fail ansi log

We probably need to validate the whole console logs color scheme. It is taken from the Campbell color scheme used by default in Windows Terminal, so there was an assumption that they had taken foreground/background contrast into consideration with their defaults. But perhaps not.

**Comment by JamesNK** [comment]
> image

What is this tool?

**Comment by tlmii** [comment]
I can't see the image you posted for some reason, but I'm assuming you're referring to my screenshot showing the color contrast checker. That's [Accessibility Insights for Windows](https://accessibilityinsights.io/docs/windows/overview/). The one for web does some good automated checks, but I use the one for windows to do more ad hoc testing.

**Comment by adamint** [comment]
> Which I think would be fine everywhere else it is used but I'm not certain

I just checked, we're still good everywhere foreground-subtext-rest is used. Reverted the neutral-layer-4 change, changed foreground-subtext-rest. 

> We probably need to validate the whole console logs color scheme

It appears that magenta (`#881798`) was the only color we needed to change. Updated to `#CD13E8`

**Comment by tlmii** [comment]
> It appears that magenta (`#881798`) was the only color we needed to change. Updated to `#CD13E8`

Might want to change light/bright magenta also as that color (`#B4009E`) is now darker than regular/dark magenta (`#CD13E8`).

**Comment by adamint** [comment]
Good call. Updated bright magenta. @tlmii for re-review

**Review by tlmii — APPROVED** [review]

**Pull request merged**
