### PR TITLE
Remove duplicate suffix append

### PR DESCRIPTION
**Pull request by WeihanLi**
Since we already append the suffix before, it would not find the executable full path when on Windows with two suffix appended

image

Before update:
image

After update:
image

### CODE REVIEW

**Comment by DamianEdwards** [comment]
FYI @mitchdenny

**Comment by JamesNK** [comment]
Does this area have tests? If so, this PR should add one for this situation. If not, we should create an issue to add tests.

**Comment by WeihanLi** [comment]
> Does this area have tests? 

Nope for now, maybe I could add a case for this in `Utils.FileUtilTests.cs` under https://github.com/dotnet/aspire/tree/main/tests/Aspire.Hosting.Tests

**Comment by WeihanLi** [comment]
One question I have when adding test cases, 
which's we expect `docker` or `docker.exe` for the full path not found on Windows?
Currently, it would be `docker.exe`

**Review by davidfowl — APPROVED** [review]
This fix looks fine but the tests I'm worried about since they are looking at the machine path.

**Review by davidfowl — CHANGES_REQUESTED** [review]
These tests are machine dependent right now. If we want to test the logic then I'd suggest passing in a fake "PATH" variable. 

```C#
FindFullPathFromPath(string command) => FindFullPathFromPath(command, Environment.GetEnvironmentVariable("PATH"));
FindFullPathFromPath(string command, string? pathVaraible) => ...
```

**Comment by WeihanLi** [comment]
> These tests are machine dependent right now. If we want to test the logic then I'd suggest passing in a fake "PATH" variable.

Since we're running `dotnet test` in the CI-agent machine, I assume the `dotnet` folder must exist in the `PATH` variable, so I use the `dotnet` executable for the test case.

We do could set the process environment variable for an override for the test case, but there's also `File.Exists` check logic, think we may need to introduce file/io system abstraction to mock it in the meantime.

To keep it simple, I just check `dotnet` for now

**Comment by davidfowl** [comment]
I would make these unit tests, unit tests and just pass in the path variable so you can write something isolated that tests the logic.

**Comment by drewnoakes** [comment]
I came across this same issue and filed #1591. Thanks @tlmii for pointing me to this existing PR.

Given the existing code does not work as intended, yet no problem is observed, perhaps we just remove the logic altogether? It's doing a bunch of probing for an executable file on the path, which the OS will do anyway.

**Comment by drewnoakes** [comment]
@WeihanLi I pushed an update to your PR that allows a unit test to make finer grained assertions about the behaviour of the function under test. Please take a look.

**Comment by WeihanLi** [comment]
@drewnoakes 👍 looks good to me, thanks very much

**Review by davidfowl — APPROVED** [review]

**Review by tlmii — APPROVED** [review]

**Pull request merged**
