### PR TITLE
Make file log change test less flaky and remove post configure from dashboard web app

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

Saw a test failure in `Configuration_FileConfigDirectoryReloadsChanges_Success` in a PR: https://dev.azure.com/dnceng-public/public/_build/results?buildId=818111&view=ms.vss-test-web.build-test-results-tab&runId=21226062&resultId=100416&paneView=debug

PR improves the delay and enabled logging. Also simplified some web app configuration.

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5933)

### CODE REVIEW

**Comment by davidfowl** [comment]
This public API we don't mind breaking yes?

**Comment by JamesNK** [comment]
No problem changing C# public API in the dashbaord.

The dashboards public API is configuration.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
