### PR TITLE
Update NodeExtensions.cs to support pnpm in addition to node and npm

### PR DESCRIPTION
**Pull request by mortenn**
## Description

As pnpm is a popular alternative to npm, I thought it would be nice to have support for it directly in the package for node.

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [x] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [x] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [x] Yes
      - [ ] No
  - [ ] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5823)

### CODE REVIEW

**Comment by mortenn** [comment]
@dotnet-policy-service agree

**Comment by mortenn** [comment]
An alternative implementation of this would be to parametrize the command argument, rather than hard coding `npm` in the existing extension method, let me know if you rather prefer that option and I'll update the PR accordingly.

**Comment by davidfowl** [comment]
@mortenn If you could propose an API that would be great. There has been at least 3 or 4 PRs like this but they were very incomplete:

- No [API proposal[(https://github.com/dotnet/aspire/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api-proposal.md&title=)
- No tests
- No sample usage
- No model for extension (when the idea of adding a extensibility model was proposed)

**Comment by mortenn** [comment]
Sure thing @davidfowl I'll look into that!

**Comment by mortenn** [comment]
superceded by the CommunityToolkit package [CommunityToolkit.Aspire.Hosting.NodeJS.Extensions](https://learn.microsoft.com/en-gb/dotnet/aspire/community-toolkit/hosting-nodejs-extensions?tabs=dotnet-cli%2Cyarn)

**Pull request closed without merging**
