### PR TITLE
Allow WithReference for AWS CDK Stack resources

### PR DESCRIPTION
**Pull request by vlesierse**
cc @normj

## Description

AWS CDK construct resources are only supported using `WithReference` & `WithEnvironment` on Project resources. A common scenario would be that you are adding an existing AWS CDK stack to Aspire and that you would like to reference exposed constructs and values from that stack to projects in Aspire. This fix changes the contract from `IResourceBuilder<IConstructResource<TConstruct>>` to `IResourceBuilder<IResourceWithConstruct<TConstruct>>` which also applies to `IStackResource`

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var stack = builder.AddAWSCDKStack("custom", scope => new CustomStack(scope, "Aspire-custom"));
builder.AddProject<Projects.Frontend>("frontend")
    .WithReference(stack, s => s.Bucket.BucketName, "BucketName")

builder.Build().Run();
```

Fixes # (issue)

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x]  No
- Did you add public API?
  - [x] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [x] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [x] Yes
      - [ ] No
  - [ ] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5951)

### CODE REVIEW

**Review by normj — APPROVED** [review]
So this adds the use case where before I could add references with delegates to individual constructs like a topic but now I can also add the reference with the delegate referencing the top level stack and then in the delegate navigate to what I want to reference.

**Comment by vlesierse** [comment]
> So this adds the use case where before I could add add references with delegates to individual constructs like a topic but now I can also add the reference with the delegate referencing the top level stack and then in the delegate navigate to what I want to reference.

Yes, it makes using stacks referenced from other projects and referencing the outputs a lot easier.

**Review by davidfowl — APPROVED** [review]

**Comment by davidfowl** [comment]
Tks!

**Pull request merged**
