### PR TITLE
Extract Aspire.Hosting.Garnet.Tests project

### PR DESCRIPTION
**Pull request by Alirexaa**
Contributes to https://github.com/dotnet/aspire/issues/3185
Contributes to https://github.com/dotnet/aspire/issues/4294

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4871)

### CODE REVIEW

**Comment by Alirexaa** [comment]
@eerhardt, we need to import `microsoft/garnet:1.0` to `netaspireci.azurecr.io`.

**Comment by Alirexaa** [comment]
This PR needs more work to do:
Garnet `WithPersistence` does not work according to https://github.com/dotnet/aspire/issues/4870.
We need to fix that and then add a functional test for that.

**Comment by eerhardt** [comment]
> @eerhardt, we need to import `microsoft/garnet:1.0` to `netaspireci.azurecr.io`.

We reference microsoft/garnet from `ghcr.io` and not DockerHub. So we shouldn't need to use our docker hub mirror.

**Comment by eerhardt** [comment]
Can we remove the reference from

https://github.com/dotnet/aspire/blob/f38b6cba86942ad1c45fc04fe7170f0fd4ba7c0b/tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj#L32

**Comment by Alirexaa** [comment]
Can i fix #4870 in this PR?
@eerhardt

**Comment by eerhardt** [comment]
> Can i fix #4870 in this PR? @eerhardt

I'd prefer if they were separate. One PR == one change. So make a PR that extracts the tests. And another PR that fixes the issue.

**Comment by Alirexaa** [comment]
> > Can i fix #4870 in this PR? @eerhardt
> 
> I'd prefer if they were separate. One PR == one change. So make a PR that extracts the tests. And another PR that fixes the issue.

I will send another PR for that.

**Comment by Alirexaa** [comment]
@eerhardt, please take a look, this should be enough at this moment.

**Review by eerhardt — COMMENTED** [review]
Thanks for the contribution, @Alirexaa.

Can you also add functional tests for WithDataVolume and WithDataBindMount?

**Comment by Alirexaa** [comment]
> Thanks for the contribution, @Alirexaa.
> 
> Can you also add functional tests for WithDataVolume and WithDataBindMount?

I will do, but those tests not pass until #5087

**Comment by eerhardt** [comment]
> I will do, but those tests not pass until https://github.com/dotnet/aspire/pull/5087

oh right. I forgot about that.  Sorry.

**Review by eerhardt — APPROVED** [review]
LGTM. Thanks again!

**Pull request merged**
