### PR TITLE
Add multi targeting for .NET Standard, .NET 4.6.2 to Service Discovery

### LINKED ISSUE #1831: Increase target frameworks
## Is your feature request related to a problem? Please describe.
I am unable to consider moving steeltoe to use Microsoft service discovery due to the very limited target frameworks supported.

## Describe the solution you'd like
I would like to be able to use Microsoft service discovery library with projects older than net 8 in a similar manner to which configuration etc works.

## Describe alternatives you've considered
N/a

## Additional context
Is a Blocker for https://github.com/SteeltoeOSS/Steeltoe/issues/1254

### PR DESCRIPTION
**Pull request by prochnowc**
This PR adds multi targeting to the Service Discovery libraries.

It follows other Microsoft.Extensions libraries regarding target framework compatibility.

Fixes #1831 

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2267)

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@prochnowc Thanks for opening this PR! Looks like you have a couple of warnings suggesting to use the APIs you replaced. You can add a suppression in the targets file to address this.

Something like:

```xml
  <PropertyGroup>
    <!-- Ignore analyzers that recommend APIs introduced in .NET Core when targeting frameworks that lack those APIs
         to avoid issues with multitargeting.
    -->
    <NoWarn Condition="$(TargetFrameworks.Contains('net4')) or $(TargetFrameworks.Contains('netstandard'))">$(NoWarn);CA1510;CA1511;CA1512;CA1513;CA1845;CA1846;CA1847</NoWarn>
  </PropertyGroup>
```

I tried to push to this PR but I don't have permission to push to your fork.

**Comment by adityamandaleeka** [comment]
@joperezr I'm seeing some errors about UpdateXlf when I try to build this locally. Seems like xliff-tasks gets pulled in automatically but it's missing the actual implementation of the target. Any ideas?

> error MSB4057: The target "UpdateXlf" does not exist in the project.

**Comment by prochnowc** [comment]
@dotnet-policy-service agree

**Comment by prochnowc** [comment]
@adityamandaleeka I've added the suppressions and did some more fixes. Some unit tests are failing only for net6.0, unfortunately I cannot the the test failures in Azure Pipelines.

**Comment by joperezr** [comment]
> It follows other Microsoft.Extensions libraries regarding target framework compatibility.

@prochnowc can you please help clarify this? While some of the Microsoft.Extensions libraries in dotnet/runtime repo target .NET Standard, newer Microsoft.Extensions libraries in the dotnet/extensions repo don't (and instead just target net6.0 and net462). The main reason is that the net result of targeting .NET Standard as well would mostly just add support for Target frameworks which are now out of support (like .NET Core 2.0, 2.1, 3.0, 5.0 and .NET Farmework 4.6.1) and some other TFM's that aren't really relevant for these libraries like Xamarin. For these reasons, I'd argue that we should also consider doing the same with these libraries and not targeting .NET Standard.

cc: @ericstj

**Comment by danmoseley** [comment]
@prochnowc Do you have a scenario in which you intend to use SD on .NET Framework ?

**Comment by prochnowc** [comment]
@danmoseley Yes, we have a .NET Framework app which we want to run in Aspire (as an Executable). This app should be able to resolve other services run in Aspire.

**Comment by mitchdenny** [comment]
@ReubenBond @joperezr @prochnowc is this PR still relevant? If not we should probably close it.

**Comment by thompson-tomo** [comment]
I feel that it is still relevant  as by making this change we are enabling third parties to maintain their current supported frameworks and move to the Microsoft approach. An example I am thinking of is Steeltoe which if framework was possible Netflix Eureka etc would become a supported service discovery registry.

**Comment by joperezr** [comment]
I agree there is value in doing this, especially if we are planning on eventually moving this library to a more general repo (like dotnet/extensions) in the future as that would make it follow precedent.

**Comment by eerhardt** [comment]
@adityamandaleeka @ReubenBond - what is the plan to add netstandard targets to ServiceDiscovery?

**Comment by davidfowl** [comment]
@ReubenBond @adityamandaleeka Are we going to support netstandard? If so then we should prioritize the issue. I'm going to close this PR because it very out of date with the current code base.

**Comment by joperezr** [comment]
In this thread looks like the effort was mostly about supporting .Net Framework, which in that case I probably rather target net462 directly (as opposed to netstandard) in order to avoid pulling in the façades.

**Comment by eerhardt** [comment]
I'd recommend we follow our own guidance (or change the guidance) - 

https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#net-and-net-standard-targets

> ✔️ DO start with including a netstandard2.0 target.

**Comment by joperezr** [comment]
@terrajobst care to comment here? Context: Microsoft.Extensions.ServiceDiscovery is a library we ship OOB and currently only targets `net8.0` but there are scenarios where people want to target .NET Framework too. That said, there are not clear scenarios (that I'm aware of) for library developers to take a dependency on it since it would instead most likely be a reference for app developers, so is the guidance that @eerhardt pointed out above still relevant (and applicable) in our case?

**Comment by terrajobst** [comment]
If we want to / need to support .NET Framework, then yes, I think we should target .NET Standard 2.0 rather than dual targeting .NET 8 and .NET Framework.

I'm out of touch with .NET Framework EOL. If the oldest supported version is .NET Framework 4.7.2 (or later) then just targeting .NET Standard 2.0 makes sense. If there is an older .NET Framework >= 4.6.1 and < 4.7.2 that is still supported, we should add a target for it as well (due to the fun problems of consuming .NET Standard 2.0 from before .NET Framework 4.7.2).

**Comment by joperezr** [comment]
Are requiring binding redirects and using facades not a concern any longer? In dotnet/runtime, we used to have this rule where all packages that targeted .NET Standard would also cross compile for netfx, in favor of not requiring binding redirects or the use of facades. We followed that same rule in dotnet/extensions. Are you saying that is no longer a concern?

**Comment by terrajobst** [comment]
Nothing beyond adding a folder + binary for .NET Framework. BRs/facades are handled by MSBuild.

**Pull request closed without merging**
