### PR TITLE
Handle cases when there's no exit code

### PR DESCRIPTION
**Pull request by davidfowl**
## Description

WaitForCompletion should handle cases where a dependency enters a terminal state but there's no exit code.

Follow up to https://github.com/dotnet/aspire/pull/5515
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5576)

### CODE REVIEW

**Comment by radical** [comment]
Test [failing](https://dev.azure.com/dnceng-public/public/_build/results?buildId=800564&view=ms.vss-test-web.build-test-results-tab&runId=20649544&resultId=100063&paneView=debug) here.
And similar test failing on main https://github.com/dotnet/aspire/issues/5577 . jfyi in case there is a pattern for these `WaitFor*` tests.

**Comment by davidfowl** [comment]
I saw it locally a few times, there must be an existing issue.

**Comment by mitchdenny** [comment]
I'm not entirely sure this is `WaitFor` causing this. When I first saw this I ran the test locally until it failed and it didn't. I suspect that some infra level failures with Docker (possibly pulling images) can case these kinds of issues. But its speculation at this point. It could also be some kind of concurrency issue when you have multiple tests running simultaneously but I haven't been able to narrow it down.

**Review by mitchdenny — APPROVED** [review]

**Comment by davidfowl** [comment]
@radical With logging:

```
| [2024-09-07T06:25:28] Aspire.Hosting.DistributedApplication Information: Aspire version: 9.0.0-ci
| [2024-09-07T06:25:28] Aspire.Hosting.DistributedApplication Information: Distributed application starting.
| [2024-09-07T06:25:28] Aspire.Hosting.DistributedApplication Information: Application host directory is: D:\a\_work\1\s\tests\Aspire.Hosting.Tests
| [2024-09-07T06:25:28] Microsoft.Extensions.Hosting.Internal.Host Error: Hosting failed to start
| Aspire.Hosting.DistributedApplicationException: Container runtime 'docker' could not be found. The error from the container runtime check was: exec: "docker": executable file not found in %PATH%
failed to start Docker command 'Status'.
| See https://aka.ms/dotnet/aspire/containers for more details on supported container runtimes.
|    at Aspire.Hosting.Dcp.DcpDependencyCheck.EnsureDcpContainerRuntime(DcpInfo dcpInfo) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 205
|    at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 110
|    at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 130
|    at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
|    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
|    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

**Pull request merged**
