### PR TITLE
Publish build assets in the build stage

### PR DESCRIPTION
**Pull request by RussKie**
As per offline discussion with @mmitche. This is a build optimisation.

* Before 1ES:
image
* With 1ES:
image

* After:
image

Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2419842&view=logs&j=d17d50ef-afac-5d4b-95a6-3014ce5cf7a4&t=95fe4740-169e-5ca1-2f88-330db40deac4
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3334)

### CODE REVIEW

**Comment by mmitche** [comment]
Build doesn't look quite right. Let me investigate.

**Comment by mmitche** [comment]
@RussKie you need to add publishAssetsImmediately to the jobs.yml template parameter set: https://github.com/dotnet/aspire/pull/3334/files#diff-05b01f3df74638712b635c705c3af6dcdaf5e3aa2d40579e7af8d75588a0cd81R127

**Comment by RussKie** [comment]
Take two - removing the post build job as it's not doing anything.

**Review by mmitche — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you @mmitche

**Pull request merged**
