### PR TITLE
Allow collapsing operations in the trace view

### LINKED ISSUE #439: Allow collapsing operations in the trace view
I want to be able to collapse the trace at any level so I can focus on pieces at a time. For e.g. in the trace below I'd love to be able to minimize the first 2 calls to figure out why there are so many db queries.

image

### PR DESCRIPTION
**Pull request by stbau04**
Allow collapsing operations in the trace view:

Fixed: https://github.com/dotnet/aspire/issues/439
Description: Adds a +/- before span that can be collapsed (if it has any children) 
- click the +/- to collapse the span (clicking the +/- does not open the details for the specific span)
- the state of a span (whether it is collapsed) stays the same even if the parent span is collpased/opened again

grafik

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1323)

### CODE REVIEW

**Comment by davidfowl** [comment]
@stbau04 Sorry for the long delay but can you update the PR? 

@JamesNK @tlmii can you review please?

**Comment by stbau04** [comment]
Updated the PR -> Collapse operation with server icons:
grafik

**Comment by JamesNK** [comment]
I pushed an update to fix a couple of minor issues:
* Changed div to span to fix displaying ellipsis on text overflow
* Removed negative margin

There is a bigger issue to resolve and that's what happens if the data refreshes while the page is open. For example, you're viewing a trace that is in progress and more spans are being added to it.

At the moment the page's data is completely refreshed, including flags that indicate whether a span is collapsed or not. Need to preserve that state on update.

**Comment by JamesNK** [comment]
I pushed an update to fix a couple of minor issues:
* Changed div to span to fix displaying ellipsis on text overflow
* Removed negative margin

image

I think there is a bigger issue to resolve and that's what happens if the data refreshes while the page is open. For example, you're viewing a trace that is in progress and more spans are being added to it.

At the moment the page's data is completely refreshed, including flags that indicate whether a span is collapsed or not. Need to preserve that state on update.

**Comment by JamesNK** [comment]
I'll attempt to fix this with a list of collapsed span ids that persists between data updates.

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
@stbau04 I think this is ready to go. Let me know if you have any feedback on the changes.

**Comment by JamesNK** [comment]
@adamint There is a clickable span in this change. Some changes might be required for accessibility. Are you ok with doing that in a follow up PR?

**Comment by stbau04** [comment]
@JamesNK I am not sure about the margin changes. Now there are small inconsistencies between server and client spans:
- With server spans, the "-" is placed a few pixel further left (as the 5px margin are missing) and therefore does not align with the clients
- There is a bigger space between the "-" and the server icon in comparison to the client spans

grafik

I think this is because the 5px margin is added on the left side of the "-" but should actually be on the right side. Or is it intentional as it is?

Apart from that the changes are looking good to me

**Comment by JamesNK** [comment]
Yes, it was on the wrong side. Updated:
image

I measured and spaces are now consistent.

**Comment by stbau04** [comment]
Thanks, now its looking good

**Pull request merged**
