### PR TITLE
Fix filter encoding with colon and plus characters

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

I noticed that log and trace filters with serialization control characters (`+`, `:`) were broken.

Blazor's `[SupplyParameterFromQuery]` feature unescapes the value before giving it to us, which causes deserialization to break. For example:

* Query string value: `name:condition:before%3Aafter`
* Parameter value: `name:condition:before:after`

If you have a filter with one of these characters in it and you refresh the browser, the filter disappears because it expects 3 colons.

This PR:

* Double encodes and decodes these special characters
* Adds tests

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5976)

### CODE REVIEW

**Comment by davidfowl** [comment]
cc @javiercn  @SteveSandersonMS @MackinnonBuck

**Comment by SteveSandersonMS** [comment]
@JamesNK Yes, I think it will be necessary to do something like this. Any value that you put in a querystring needs to be encoded for querystrings.

To be honest I would look at `DashboardUrls.StructuredLogsUrl` and try to make it a bit less coupled to particular expectations for `filters` being pre-encoded. If this took care of encoding as part of constructing the URI, then the caller wouldn't need to know about this. In theory as long as the encoding happens at the point where you build the URI, then whenever you code later receives the querystring value, it will decode to whatever was supplied to this method, so you don't need to hardcode rules about what gets encoded at other places.

**Comment by JamesNK** [comment]
The reason we didn't encode the whole filter query string when adding it to the URL is it becomes a bit of a dissater to read:

Before:

> filters=log.message:contains:Application%20started.%20Press%20Ctrl%252BC%20to%20shut%20down.%2Blog.message:contains:Hosting%20environment%253A%20Development

After:

> filters=log.message%3Acontains%3AApplication%2520started.%2520Press%2520Ctrl%252BC%2520to%2520shut%2520down.%20log.message%3Acontains%3AHosting%2520environment%253A%2520Development

Although I guess once values require a lot of escaping neither are really readable.

**Comment by JamesNK** [comment]
Updated. I think this is better and safer, although URLs don't look quite as good. Given the trouble that special characters have caused in this query string value, it's better to just be safe.

Could improve in the future by using an encoder which doesn't escape `:` and `+` characters, but we'd need to copy `AddQueryString` out of Blazor source. Not important.

**Review by mitchdenny — APPROVED** [review]
LGTM. More of a side comment renames from *LogFilter to Filter (non blocking)?

**Comment by JamesNK** [comment]
The rename of "Log filter" -> "Filter" is because filters are used on structured logs and traces pages now. I didn't feel like creating a new PR just to rename stuff 😄

**Pull request merged**
