### PR TITLE
Move shared code to shared directory

### LINKED ISSUE #1711: Move Aspire.Dashboard and Aspire.Hosting shared code to src/Shared
Aspire.Dashboard and Aspire.Hosting are sharing some code in each direction out of the other project.

Move shared code to src/Shared directory to reduce the chance of unexpected changing the behavior of the other app when editing shared files.

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspire/issues/1711
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1751)

### CODE REVIEW

**Comment by davidfowl** [comment]
If this conflicts with anything being done in the dashboard OOP branch we should hold off.

**Comment by JamesNK** [comment]
I looked at https://github.com/dotnet/aspire/compare/main...feature/dashboard-oop and it appears like it doesn't. The branch adds some new shared files, but I'll add a comment when there is a PR merging to main that they need to be moved.

**Comment by JamesNK** [comment]
Updated after dashboard oop merge.

**Comment by mitchdenny** [comment]
Approving, but will need to pick up latest changes from main as there is a new playground project (SqlServerEndToEnd).

**Review by mitchdenny — APPROVED** [review]

**Pull request merged**
