### PR TITLE
Make the manifest file clickable in terminal

### PR DESCRIPTION
**Pull request by Kahbazi**
I'm lazy 😅 ! I thought it would be a good feature to be able to click on the generated manifest file in the terminal and open it instead of copy and paste the path.
Old:
image
New:
image

### CODE REVIEW

**Comment by smitpatel** [comment]
Questions:
Does it work across different platforms correctly?
Does it work across different terminals correctly?
What happens when the *.json file are not associated with default app?

**Comment by davidfowl** [comment]
I'm not a fan, none of the other paths look like this. I don't think we should take it.

**Comment by tlmii** [comment]
> I'm not a fan, none of the other paths look like this. I don't think we should take it.

Windows Terminal by default doesn't automatically make local paths (e.g. `c:\whatevever\`) clickable. To get the automatic hyperlinks you'd have to use `file:///` scheme. Which, I agree, doesn't look great when we use normal local paths everywhere else. You can always use the escape sequences to do it and leave it looking however you want:

image

You could even do
image

The (quick and dirty) code for the first screenshot above is:

```C#
var fullyQualifiedPath = Path.GetFullPath(_options.Value.OutputPath);
var uri = new Uri(fullyQualifiedPath);
_logger.LogInformation("Published manifest to: \x1B]8;;{manifestUriPath}\x1B\\{manifestPath}\x1B]8;;\x1B\\", uri, fullyQualifiedPath);
````

The downside here is that since the support for hyperlinks is terminal dependent and the fallback text is variable depending on implementation, I probably wouldn't recommend any of this. Here's what the above looks like in cmd.exe:

image

**Comment by danmoseley** [comment]
> Windows Terminal by default doesn't automatically make local paths (e.g. c:\whatevever\) clickable

A setting for that in Windows terminal seems like the right fix (for windows terminal anyway). Is there one? If not I assume they've gotten requests.
I'm going to close this meantime as I think we don't want the file prefix.

**Pull request closed without merging**
