### PR TITLE
Upgrade npgsql to 8.0.3

### PR DESCRIPTION
**Pull request by amcasey**
Effectively a backport of #4194.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4283)

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
This assumes we will release an 8.0.1 (8.0.2 I think)? As 8.1 is still in main.

**Comment by danmoseley** [comment]
> This assumes we will release an 8.0.1 (8.0.2 I think)? As 8.1 is still in main.

@joperezr ?

**Comment by sebastienros** [comment]
I think we should put it in main and then decide to backport it or not.  

NB: 8.0.1 was already released (at the same time as 8.0.0), next patch version 8.0.2 is not yet decided (AFAIK).

**Comment by joperezr** [comment]
Correct, it is not yet decided if we'll ship a patch next month or not. If we do, it'll be from this branch. If we don't then this branch is essentially dead-ended. My suggestion is to keep this PR open in case we do end up deciding to ship a patch, and if so we merge.

**Comment by eerhardt** [comment]
Closing as we are shipping 8.1 this week which already contains this change.

**Pull request closed without merging**
