### PR TITLE
Add public API tracking

### PR DESCRIPTION
**Pull request by drewnoakes**
This adds the `Microsoft.CodeAnalysis.PublicApiAnalyzers` package to the dashboard and hosting projects, though it could be added more broadly if deemed helpful.

As we approach v1, we should be very intentional about what APIs are expected to be public. I have the feeling that several public APIs we have today don't need to be public and that we may regret making them public in future when we want to change them but cannot easily do so due to backwards compatibility goals.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1828)

### CODE REVIEW

**Comment by drewnoakes** [comment]
Converting to a draft due to issues in generated code, which I wouldn't expect. I've pinged @mavasani offline to see if this is expected.

**Comment by mitchdenny** [comment]
Very supportive of getting this in. I think this will be critical in the post P4 period.

**Comment by danmoseley** [comment]
@drewnoakes did you find out why you were seeing those issues? I cleared milestone meantime.

**Comment by mitchdenny** [comment]
I don't think we need this PR now as I merged this in last week.

**Pull request closed without merging**
