### PR TITLE
Adding wps extension

### LINKED ISSUE #1063: Support for Azure Web PubSub service
- [x] Component support
- [ ] Provision support
- [ ] Advanced: Event handler support

### PR DESCRIPTION
**Pull request by vicancy**
For https://github.com/dotnet/aspire/issues/1063

### CODE REVIEW

**Comment by DamianEdwards** [comment]
@vicancy can you please open an issue to track this work?

**Comment by eerhardt** [comment]
What's the difference between:

* https://www.nuget.org/packages/Azure.Messaging.WebPubSub
* https://www.nuget.org/packages/Azure.Messaging.WebPubSub.Client

?

**Comment by vicancy** [comment]
> What's the difference between:
> 
> * https://www.nuget.org/packages/Azure.Messaging.WebPubSub
> * https://www.nuget.org/packages/Azure.Messaging.WebPubSub.Client
> 
> ?

image

**Comment by vicancy** [comment]
Hi Eric @eerhardt , I am trying to add provisioning part into the PR, however failed with error package 'Azure.ResourceManager.WebPubSub' is not found in the configured package sources. Could you help to add this control plane package for Web PubSub?

**Comment by mitchdenny** [comment]
This still needs app model extensions. Once this gets a bit further along, we'll also want a tracking issue over in azure/azure-dev around AZD deployment tool support.

**Pull request closed without merging**
