### PR TITLE
Remove unused resources

### PR DESCRIPTION
**Pull request by RussKie**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4057)

### CODE REVIEW

**Comment by RussKie** [comment]
Should we take this into release/8.0 as well?

**Comment by joperezr** [comment]
Great find, thanks for fixing @RussKie. Regarding 8.0, I really doubt this meets the bar as that branch is pretty much locked now, but still good to have this in 8.1

**Review by sebastienros — APPROVED** [review]

**Comment by danmoseley** [comment]
How did you find them @RussKie

**Comment by RussKie** [comment]
> How did you find them @RussKie

Magic :)


Kidding. It was an artifact of the [work](https://dev.azure.com/SupportabilityCheckList/Azure%20Compute/_workitems/edit/196934) you roped me into :)

**Pull request merged**
