### PR TITLE
Support transports from individual kestrel endpoints

### LINKED ISSUE #4470: Support reading transports from individual kestrel endpoint configuration
Follow up from https://github.com/dotnet/aspire/pull/4438

As part of parsing the kestrel configuration, we should be parsing the protocols enum under individual endpoints as well as the endpoint default section. e.g:

```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "Endpoints": {
      "http": {
        "Url": "http://localhost:5009"
      },
      "grpc": {
        "Protocols": "Http2",
        "Url": "http://localhost:5008"
      }
    }
  }
}
```

AppHost

```C#
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject<Projects.WebApplication1>("api");

builder.Build().Run();
```

Manifest

```JSON
{
  "$schema": "https://json.schemastore.org/aspire-8.0.json",
  "resources": {
    "api": {
      "type": "project.v0",
      "path": "../Mongo.ApiService/Mongo.ApiService.csproj",
      "env": {
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY": "in_memory",
        "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true",
        "Kestrel__Endpoints__grpc__Url": "http://*:{api.bindings.grpc.targetPort}",
        "Kestrel__Endpoints__http__Url": "http://*:{api.bindings.http.targetPort}"
      },
      "bindings": {
        "grpc": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "targetPort": 5008
        },
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "targetPort": 5009
        },
        "https": {
          "scheme": "https",
          "protocol": "tcp",
          "transport": "http",
          "targetPort": 5008
        }
      }
    }
  }
}
```

The transport should be http2 for the grpc binding.

### PR DESCRIPTION
**Pull request by davidebbo**
Fixes #4470
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4533)

### CODE REVIEW

**Comment by mitchdenny** [comment]
I think the `<remarks>` on `AddProject<T>(...)` need to be expanded to mention that we process the config file to apply transports to endpoints. Also it would be good to have a conceptual article on `docs-aspire` for this -- can you file an issue and link it here?

**Review by mitchdenny — APPROVED** [review]

**Comment by davidfowl** [comment]
We already have a networking article, I would expand it with this content https://github.com/dotnet/docs-aspire/blob/main/docs/fundamentals/networking-overview.md

**Comment by davidebbo** [comment]
I added a comment. I found a nice way of avoiding to have to repeat the same string in all overloads, which was totally bothering me :)

**Pull request merged**
