### PR TITLE
Null is not true, but null is not false

### PR DESCRIPTION
**Pull request by davidfowl**
Simplest fix for this so we can backport to preview 3. A better fix is to avoid making this nullable and just have true and false 😄 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2030)

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
Not needed for preview 3 branch, but for main does it make sense to also add tests for this?

**Comment by davidfowl** [comment]
I was just discussing this with @JamesNK. To enable testing this component it needs a lot more refactoring. Yes, though we need to do it.

**Comment by mitchdenny** [comment]
I think we probably need to start to break `ApplicationExecutor` up ... its become a bit of a dumping ground. In doing so we can make this whole space more testable.

**Pull request merged**
