### PR TITLE
Fix console logs after restart

### LINKED ISSUE #5803: Logs break when restarting projects
Logs for projects are lost after restarting. 

https://github.com/user-attachments/assets/3c7da8f0-b458-46ba-a210-a284522813cc

### PR DESCRIPTION
**Pull request by JamesNK**
PR changes:

* Don't complete a resource logger when a resource is deleted. The only scenario where resources are deleted right now is restart, and we still want logs to be available after a restart.
* Correctly display in-memory logs, i.e. logs written by resource logger service, when viewing the console logs page. They're no longer cleared away when console logs watch stops.

Fixes https://github.com/dotnet/aspire/issues/5803

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5909)

### CODE REVIEW

**Comment by mitchdenny** [comment]
@drewnoakes this is relevant to the conversation we were having today about health checks UX in the dashboard. Specifically this bit:

> Correctly display in-memory logs, i.e. logs written by resource logger service, when viewing the console logs page. They're no longer cleared away when console logs watch stops.

For 9.0 we might be best to just write the resource log with error messages from health checks. Previously it wasn't that great of an experience, but by persisting the log messages between visits to the logs page it changes things.

**Comment by mitchdenny** [comment]
Hrm ... this still doesn't preserve the logs from before the process starts. The `WaitFor` implementation uses the resource logger to output some messages like the following:

image

The process can finish starting up and be running and not be showing the Kestrel log outputs, but if I navigate away and come back I see this:

image

You can use the _waitfor_ playground to verify this. You need to look at the console logs quickly though before it has a chance to start (only takes about 3 seconds once the dashboard is visible).

**Comment by mitchdenny** [comment]
Subtle observation, if you catch it early enough the text in the drop down is different:

image

But once the process is running it changes to the screenshot I have up above (the first one).

**Comment by JamesNK** [comment]
The problem is in how WaitFor does logging. I created an issue for it: https://github.com/dotnet/aspire/issues/5908

The problem is that IResource doesn't know about the unique name that is generated by DCP. Maybe the value could be generated ealier and stored in an annotation. Then GetLogger(IResource) would have the right name. That wouldn't work for resources with replicas where there are multiple names.

**Comment by mitchdenny** [comment]
Hrm ... realistically if we had two replicas, both replicas would be getting held up by the same set of health checks - so we would want the log to show up in both places. We might need an API that allows us to do some kind of "aggregate logging" across replicas.

**Review by adamint — APPROVED** [review]

**Pull request merged**
