### PR TITLE
Fix broken find token image in HTTP

### LINKED ISSUE #3603: [WebToolsE2E][Aspire] When running Aspire app with http, In the pop-up browser, move the mouse to the "Where can I find the token?" and then the image cannot be displayed in the pop-up box.
**REGRESSION INFO:** This is a new feature on Aspire 8.0.0-preview.6.24210.28

**INSTALL STEPS**

1.Clean machine: Win11 x64 23h2 ENU
2.Install VS Code[1.88.0] and C#[2.26.9 main], C# Dev Kit[1.4.139 main]
3.Install SDK 8.0.204(latest-released-build)
4.Install Aspire 8.0 P6 workload version 8.0.0-preview.6.24210.28
5.Apply NuGet Feeds

**REPRO STEPS**

1.Open CMD, creating an Aspire App using following commands:
```
dotnet new aspire -o aspire1
cd aspire1
code .
```
2.Open launchSettings.json under Properties folder in xxx.AppHost, add below code:
`"ASPIRE_ALLOW_UNSECURED_TRANSPORT": "true"`
image
3.Press 'Ctrl+shift+P' > Debug: Select and Start Debugging > C# > C#: xxx.AppHost[http]
4.In the pop-up browser, move mouse to 'Where do I find the token?'

**ACTUAL:**
the image cannot be displayed in the pop-up box.
image
image

**NOTE:**
1.Run aspire project with https, it works well.
2.This issue also repro on Mac OS.

**EXPECTED**
the image can be displayed normally.
image

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspire/issues/3603

If the website is http then allow http or https images.
If the website is https then only allow https images.

Working:

image

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3635)

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

**Comment by tlmii** [comment]
Given that we don't have any external images, would just doing `'self'` be better?

**Comment by JamesNK** [comment]
'self' would have been simpler.

IMO the PR as it is works and could allow external images if needed by a feature at some point. I think we go with this for now. Change more if needed.

**Review by kvenkatrajan — APPROVED** [review]

**Comment by kvenkatrajan** [comment]
Approved and thanks for the tests. Just wondering if any XSS concerns with _any_ external site when we specify https

**Comment by danmoseley** [comment]
We missed the snap anyway, if @tlmii  you believe you need to modify this there is time.

**Comment by JamesNK** [comment]
> Approved and thanks for the tests. Just wondering if any XSS concerns with _any_ external site when we specify https

No.

**Pull request merged**
