### PR TITLE
Option for providing a path to persist data from the Azurite container

### LINKED ISSUE #1533: The `WithVolumeMount` extension method doesn't work with Azurite
If you want to persist your Azurite table/queue/blob data between app restarts you need to mount a volume from the host ([see the docs on how to do that](https://learn.microsoft.com/azure/storage/common/storage-use-azurite?tabs=docker-hub%2Cqueue-storage#run-azurite)).

With other container options you can use the extension method `WithVolumeMount`, like so:

```c#
IResourceBuilder<PostgresContainerResource> postgresContainerDefinition = builder
    .AddPostgresContainer("db")
    .WithEnvironment("POSTGRES_DB", "my_data")
    // Mount the database scripts into the container that will configure pgvector
    .WithVolumeMount("./database", "/docker-entrypoint-initdb.d", VolumeMountType.Bind);
```

But the extension method doesn't work for Azurite because it's signature is:

```csharp
public static IResourceBuilder<T> WithVolumeMount<T>(this IResourceBuilder<T> builder, string source, string target, VolumeMountType type = default, bool isReadOnly = false) where T : ContainerResource
```

And `AzureStorageResource`, which is the type when working with Azure Storage, isn't `ContainerResource`.

To solve this the `UseEmulator` method should return a type that can support `WithVolumeMount` while not accidentally supporting it if you're deploying to Azure Storage _without_ the emulator.

## Workaround

The workaround is to write out the full `WithAnnontation` call, like so:

```csharp
storage.UseEmulator()
.WithAnnotation(new VolumeMountAnnotation("./data/azurite", "/data", VolumeMountType.Bind));
```

### PR DESCRIPTION
**Pull request by aaronpowell**
Fixes #1533
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1631)

### CODE REVIEW

**Comment by davidfowl** [comment]
Why not a callback with the container resource? That way we don’t need to come back again when the next feature request comes in.

**Comment by mitchdenny** [comment]
There is no container resource, this simply adds an annotation. Any resource can be a container if it has the right annotation. I think having this as a parameter on `UseEmulator(...)` feels right - when you are using this method you are already in the context of configuring the emulator which supports this resource.

I think we should talk about options/settings patterns for builder extension methods in the offsite though - so perhaps we should hold this until next week (even though I think this is probably the right solution).

**Comment by aaronpowell** [comment]
Yep, as @mitchdenny notes, we don't have a `ContainerResource` type available here, so we can't use the existing extension method, which is why I went with the parameters.

**Comment by davidfowl** [comment]
Ah I see.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
