### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by joperezr**
Update Package dependencies.

Depending on timing, we may want to backport this to release/8.1
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4990)

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
Thanks! I would vote that we bring these dependency updates into 8.1 as well. They all should be good to update.

I assume you are going to add the new versions to the nuget mirror to get CI green.

**Comment by danmoseley** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2498780&view=results

**Review by danmoseley — APPROVED** [review]

**Comment by joperezr** [comment]
@eerhardt @sebastienros looks like not all of the images we use are in our container registry yet as my linux build is failing due to dockerhub throttling on elasticsearch one. Found the line to update to fix it, but I need to push the image first. Did we push any instructions anywhere on how to do that?

**Comment by joperezr** [comment]
nvm, figured it out, also looks like elasticsearch was already pushed.

**Comment by eerhardt** [comment]
> Did we push any instructions anywhere on how to do that?

https://github.com/dotnet/aspire/blob/main/docs/updating-container-registry.md

**Pull request merged**
