### PR TITLE
[tests] Try to fix random failures on playground tests build

### PR DESCRIPTION
**Pull request by radical**
`Aspire.Playground.Tests` build failed sometimes with errors like:

`Could not copy "D:\a\_work\1\s\artifacts\obj\CatalogModel\Release\net8.0\CatalogModel.dll" to "D:\a\_work\1\s\artifacts\bin\CatalogModel\Release\net8.0\CatalogModel.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\_work\1\s\artifacts\bin\CatalogModel\Release\net8.0\CatalogModel.dll' because it is being used by another process. The file is locked by: "Pdb2Pdb (1628)"`

The errors are not limited to this file, but can be one from any of the
playground projects.

Given:

1. `Aspire.Playgroud.Tests` references various playground AppHost projects
   directly with `AdditionalProperties="SkipDashboardProjectReference=true"`.
2. `Aspire.sln` also references these playground projects.

My thinking is that msbuild ends up treating these projects like
`TestShop/CatalogModel/CatalogModel.csproj` as two different project
instances:

1. One with `SkipDashboardProjectReference=true` (from
   `Aspire.Playground.Tests`)
2. One without that property, when building the reference directly from
   `Aspire.sln`.

This patch avoids that entirely by defaulting to
`SkipDashboardProjectReference=true` on CI, and on helix.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5271)

### CODE REVIEW

**Comment by radical** [comment]
@rainersigwald Does my reasoning for the issue make sense?

**Comment by radical** [comment]
Once this is merged, we can open a PR to re-enable the playground tests.

**Comment by radical** [comment]
> Once this is merged, we can open a PR to re-enable the playground tests.

https://github.com/dotnet/aspire/pull/5276

**Comment by radical** [comment]
Ready to merge.

**Review by RussKie — APPROVED** [review]

**Pull request merged**
