### PR TITLE
Fix path to Aspire.RuntimeIdentifier.Tool.csproj

### PR DESCRIPTION
**Pull request by radical**
From
`src\Aspire.Hosting.Sdk\Aspire.RuntimeIdentifier.Tool\Aspire.RuntimeIdentifier.Tool.csproj`
->
`src\Aspire.AppHost.Sdk\Aspire.RuntimeIdentifier.Tool\Aspire.RuntimeIdentifier.Tool.csproj`

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5911)

### CODE REVIEW

**Comment by radical** [comment]
Am I missing something here? Does the solution work for everyone without this change?

**Comment by mitchdenny** [comment]
I noticed some load errors after the workload change was merged. So I think something is needed here.

**Review by joperezr — APPROVED** [review]
Oops my bad, yes thanks for fixing @radical

**Comment by joperezr** [comment]
Oh, looks like @eerhardt already fixed this in main with https://github.com/dotnet/aspire/pull/5924

**Pull request closed without merging**
