### PR TITLE
Update container runtime not found exception message

### PR DESCRIPTION
**Pull request by DamianEdwards**
#3190
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3224)

### CODE REVIEW

**Review by timheuer — APPROVED** [review]
lgtm

**Comment by balachir** [comment]
@DamianEdwards for the scenario described in https://github.com/dotnet/aspire/issues/3190, with neither docker or podman installed, with your change, the exception message will still output `Container runtime 'docker' could not be found`. But now, there will be the additional aka.ms link with more info. Correct?

How does the '{0}' in the error message resolve to 'docker'? Is that because DCP tries to default to docker?

**Review by balachir — APPROVED** [review]

**Comment by DamianEdwards** [comment]
@balachir From my understanding, DCP attempts to auto-detect which container runtime is installed and use that, but in the case where the error coming back doesn't have a container runtime name, `Aspire.Hosting` assumes Docker as the name and then adds the link now.

**Pull request merged**
