### PR TITLE
Switch to log streaming

### PR DESCRIPTION
**Pull request by karolz-ms**
Permanently switches the dashboard to use streaming logs for local app run. 

TODO
- [x] Integrate new DCP build, which fixes log capture delay on Windows and adds support for timestamps in Container logs.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2744)

### CODE REVIEW

**Comment by karolz-ms** [comment]
(code is ready for review)

**Comment by davidfowl** [comment]
Can I do this as part of my PR? 😄

**Comment by karolz-ms** [comment]
> Can I do this as part of my PR? 😄

Sure, if you approve my DCP PR 😆

**Comment by davidfowl** [comment]
All good now!

**Comment by karolz-ms** [comment]
@davidfowl I re-worked this change based on your change. Should be ready to merge now!

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
