### PR TITLE
Fix the casing of AddKeyedAzureCosmosDBClient

### PR DESCRIPTION
**Pull request by eerhardt**
Also fix the casing in the READMEs as well.

Note that the EF Component has `AddCosmosDbContext`, but there it is a "Cosmos" "DbContext", so the casing is correct.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3897)

### CODE REVIEW

**Comment by radical** [comment]
Just curious - what is the motivation for using `DB` vs `Db` here, if efcore is already using `Db`?

**Comment by eerhardt** [comment]
> Just curious - what is the motivation for using `DB` vs `Db` here, if efcore is already using `Db`?

To be consistent with all the other places that we say "CosmosDB".

Technically, the .NET naming guidelines say that 2 letter acroynms are upper cased, like System.IO.

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers

**Review by radical — APPROVED** [review]

**Comment by eerhardt** [comment]
One other option here would be to drop `DB` and just say `AddAzureCosmosClient`. But we should probably do that everywhere - like in Aspire.Hosting.Azure.CosmosDB.

cc @mitchdenny

**Review by DamianEdwards — APPROVED** [review]
I'm happy as long as we're consistent.

**Comment by mitchdenny** [comment]
We should be consistent with https://www.nuget.org/packages/Azure.ResourceManager.CosmosDB/

**Review by danmoseley — APPROVED** [review]

**Comment by eerhardt** [comment]
> One other option here would be to drop `DB` and just say `AddAzureCosmosClient`. But we should probably do that everywhere - like in Aspire.Hosting.Azure.CosmosDB.

Closing in favor of #3906, where the Cosmos team decided to drop "DB" from the runtime component APIs.

**Pull request closed without merging**
