### PR TITLE
Rename key Service Discovery types

### PR DESCRIPTION
**Pull request by ReubenBond**
This PR renames some of the core service discovery types for clarity, to better align their names with their purpose and behavior. The existing names have made me uncomfortable since I created them, but I did not want to stall progress by bikeshedding them.

* Rename `ServiceEndPointResolver` to `ServiceEndPointWatcher`: this class watches for changes in a single service's endpoints and publishes those changes to listeners. The lifecycle of the class is controlled by the object which created it (through `ServiceEndPointResolverFactory`, which should be renamed also). When disposed, the instance stops watching for changes in service endpoints.
  * Rationale for the rename: _Resolver_ is accurate, but better suited to the next class (below) and _Watcher_ is a closer fit to the behavior and alludes to the lifetime of the object, that it actively does something while alive.
* Rename `ServiceEndPointResolverRegistry` to `ServiceEndPointResolver`: this class is intended to be the main entry point for consumers performing on-demand service discovery outside of `HttpClient`. This class is registered as a singleton. It manages the lifetime of a `ServiceEndPointWatcher` for each resolved service, disposing them when they have been unused for some period of time.
  * Rationale for the rename: The suffix _Registry_ does not fit well with the consumer-facing API which this class exposes (there is no registration action).
* Rename `IServiceEndPointResolver` to `IServiceEndPointProvider`: this interface is implemented by the actual endpoint providers (config, DNS, pass-thru) and is consumed by `ServiceEndPointWatcher`. Each `ServiceEndPointWatcher` holds possibly multiple `IServiceEndPointProvider` instances and gives each a chance to modify the resulting `ServiceEndPointCollection`.
  * Rationale for the rename: These are resolvers at their core, but the `ServiceEndPointResolver` name seems more fit for the above class and since it does not implement this interface, I think it's best to choose a distinct name (it feels odd that `ServiceEndPointResolver` doesn't implement `IServiceEndPointResolver` when both exist). I also considered `IServiceEndPointSource` but _Provider_ seemed more appropriate.

Of course, I'm amenable to naming suggestions.

For PR reviewers, it is easier to review individual commits, since the combined diff is confusing due to the A -> B + C ->A rename.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1877)

### CODE REVIEW

**Comment by amcasey** [comment]
I'm not sure I understand what a provider is.  The first two seem much clearer than the old names.

**Comment by DamianEdwards** [comment]
`Provider` is a suffix we use consistently in `Microsoft.Extensions.*` and `Microsoft.AspNetCore.*` to represent types that provide implementations to some factory-like abstraction, e.g. `ILoggerProvider`, `IConfigurationProvider`, `IModelTypeProvider`, `ITempDataProvider`, etc.

**Comment by davidfowl** [comment]
This seems important to merge

**Comment by joperezr** [comment]
Friendly reminder that this PR is assigned to the Preview 4 milestone which is snapping in a couple of hours. Please ensure it is merged by 4pm PST in order to ensure the change will be part of Preview 4.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
