### PR TITLE
[release/8.0] Remove constraint from templates for 8.0.1

### PR DESCRIPTION
**Pull request by joperezr**
Branding changes for 8.0.1 and backports https://github.com/dotnet/aspire/pull/4176 to fix template constraints to avoid SDK bug.

cc: @DamianEdwards @danmoseley 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4181)

### CODE REVIEW

**Comment by danmoseley** [comment]
test failures are like
```
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.Confluent.Kafka (>= 8.0.0) but Aspire.Confluent.Kafka 8.0.0 was not found. An approximate best match of Aspire.Confluent.Kafka 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.Microsoft.Azure.Cosmos (>= 8.0.0) but Aspire.Microsoft.Azure.Cosmos 8.0.0 was not found. An approximate best match of Aspire.Microsoft.Azure.Cosmos 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.Microsoft.Data.SqlClient (>= 8.0.0) but Aspire.Microsoft.Data.SqlClient 8.0.0 was not found. An approximate best match of Aspire.Microsoft.Data.SqlClient 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.MongoDB.Driver (>= 8.0.0) but Aspire.MongoDB.Driver 8.0.0 was not found. An approximate best match of Aspire.MongoDB.Driver 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.MySqlConnector (>= 8.0.0) but Aspire.MySqlConnector 8.0.0 was not found. An approximate best match of Aspire.MySqlConnector 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.Npgsql (>= 8.0.0) but Aspire.Npgsql 8.0.0 was not found. An approximate best match of Aspire.Npgsql 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.Npgsql.EntityFrameworkCore.PostgreSQL (>= 8.0.0) but Aspire.Npgsql.EntityFrameworkCore.PostgreSQL 8.0.0 was not found. An approximate best match of Aspire.Npgsql.EntityFrameworkCore.PostgreSQL 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.Oracle.EntityFrameworkCore (>= 8.0.0) but Aspire.Oracle.EntityFrameworkCore 8.0.0 was not found. An approximate best match of Aspire.Oracle.EntityFrameworkCore 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.Pomelo.EntityFrameworkCore.MySql (>= 8.0.0) but Aspire.Pomelo.EntityFrameworkCore.MySql 8.0.0 was not found. An approximate best match of Aspire.Pomelo.EntityFrameworkCore.MySql 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.RabbitMQ.Client (>= 8.0.0) but Aspire.RabbitMQ.Client 8.0.0 was not found. An approximate best match of Aspire.RabbitMQ.Client 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj : error NU1603: Warning As Error: TestProject.IntegrationServiceA depends on Aspire.StackExchange.Redis (>= 8.0.0) but Aspire.StackExchange.Redis 8.0.0 was not found. An approximate best match of Aspire.StackExchange.Redis 8.0.1 was resolved. [/datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj]
[restore]   Failed to restore /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj (in 24.87 sec).
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.AppHost (>= 8.0.0) but Aspire.Hosting.AppHost 8.0.0 was not found. An approximate best match of Aspire.Hosting.AppHost 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.Azure (>= 8.0.0) but Aspire.Hosting.Azure 8.0.0 was not found. An approximate best match of Aspire.Hosting.Azure 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.Azure.CosmosDB (>= 8.0.0) but Aspire.Hosting.Azure.CosmosDB 8.0.0 was not found. An approximate best match of Aspire.Hosting.Azure.CosmosDB 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.Kafka (>= 8.0.0) but Aspire.Hosting.Kafka 8.0.0 was not found. An approximate best match of Aspire.Hosting.Kafka 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.MongoDB (>= 8.0.0) but Aspire.Hosting.MongoDB 8.0.0 was not found. An approximate best match of Aspire.Hosting.MongoDB 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.MySql (>= 8.0.0) but Aspire.Hosting.MySql 8.0.0 was not found. An approximate best match of Aspire.Hosting.MySql 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.NodeJs (>= 8.0.0) but Aspire.Hosting.NodeJs 8.0.0 was not found. An approximate best match of Aspire.Hosting.NodeJs 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.Oracle (>= 8.0.0) but Aspire.Hosting.Oracle 8.0.0 was not found. An approximate best match of Aspire.Hosting.Oracle 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.PostgreSQL (>= 8.0.0) but Aspire.Hosting.PostgreSQL 8.0.0 was not found. An approximate best match of Aspire.Hosting.PostgreSQL 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.RabbitMQ (>= 8.0.0) but Aspire.Hosting.RabbitMQ 8.0.0 was not found. An approximate best match of Aspire.Hosting.RabbitMQ 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.Redis (>= 8.0.0) but Aspire.Hosting.Redis 8.0.0 was not found. An approximate best match of Aspire.Hosting.Redis 8.0.1 was resolved.
[restore] /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj : error NU1603: Warning As Error: TestProject.AppHost depends on Aspire.Hosting.SqlServer (>= 8.0.0) but Aspire.Hosting.SqlServer 8.0.0 was not found. An approximate best match of Aspire.Hosting.SqlServer 8.0.1 was resolved.
[restore]   Failed to restore /datadisks/disk1/work/B74F09FD/w/A52B093F/e/testassets/testproject/TestProject.AppHost/TestProject.AppHost.csproj (in 20.84 sec).


```

**Comment by danmoseley** [comment]
this doesn't make logical sense? at a minimum the error message should be improved:
`depends on XXX (>= 8.0.0) but XXX 8.0.0 was not found. An approximate best match of XXX 8.0.1 was resolved.`
whatever the fix on our side, do we need a bug against nuget for the message

**Comment by joperezr** [comment]
Oh yes thanks! I know what's wrong, I missed one tiny change, will add in a bit.

**Comment by DamianEdwards** [comment]
@danmoseley that message is saying "you asked for 8.0.0 but I couldn't find an 8.0.0 in any configured feed, but I did find an 8.0.1 which is valid according to NuGet default rules where the version specified is actually the minimum version"

**Review by DamianEdwards — APPROVED** [review]

**Comment by danmoseley** [comment]
> "you asked for 8.0.0 but I couldn't find an 8.0.0 in any configured feed, but I did find an 8.0.1 which is valid according to NuGet default rules where the version specified is actually the minimum version"

I figured, then I think the `but` and `approximate` makes that not clear. maybe eg
`...depends on XXX (>= 8.0.0). XXX 8.0.0 was preferred but not found. A next best match of XXX 8.0.1 was resolved.`

**Comment by danmoseley** [comment]
https://github.com/NuGet/Home/issues/13446 fwiw

**Pull request merged**
