### PR TITLE
Bump templates package references

### PR DESCRIPTION
**Pull request by sebastienros**
Was reviewing templates and checked versions. Should be ok to bump once in a while.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4782)

### CODE REVIEW

**Comment by sebastienros** [comment]
@DamianEdwards do we have automated tests for these or should I check each of them locally?

**Comment by DamianEdwards** [comment]
@sebastienros tests were added by @radical I believe?

**Comment by DamianEdwards** [comment]
There's a reason the test packages aren't kept up to date apparently but adding @timheuer for context

**Comment by timheuer** [comment]
@Evangelink for Aspire-specifically, do you think we should keep the test packages up-to-date? It doesn't seem to fall into the scenarios you noted why we don't update them for all?

**Comment by Evangelink** [comment]
It seems fine for me to be on latest here. You will have to either do update PRs often or to update your infra (dependabot maybe) to have updates.

**Comment by Evangelink** [comment]
> There's a reason the test packages aren't kept up to date apparently but adding @timheuer for context

Long story short, it was hard to get approval to bug fix SDK to bring new versions of NuGet packages. And the release cycle of ask doesn't match updates of framework packages. 

Lastly, it's not allowed to be using floating versions.

We are happy to revise our strategy if you have other recommendations or if we can get help with approvals.

**Comment by DamianEdwards** [comment]
> Long story short, it was hard to get approval to bug fix SDK to bring new versions of NuGet packages. And the release cycle of ask doesn't match updates of framework packages.

Hmm that seems like something that should be revisited as shipping templates with out-of-date (i.e. unsupported) package references seems less than ideal. I thought other templates were getting their dependencies updated as part of SDK feature band releases but checking the [history for ASP.NET Core templates](https://github.com/dotnet/aspnetcore/tree/release/8.0/src/ProjectTemplates/Web.ProjectTemplates) suggests I'm wrong. Adding @mkArtakMSFT for confirmation on what we do for ASP.NET Core templates.

**Comment by radical** [comment]
> @sebastienros tests were added by @radical I believe?

Yes - https://github.com/dotnet/aspire/blob/c76edc2159176d91b683ee63ead8fa641e34ebca/tests/Aspire.Workload.Tests/PerTestFrameworkTemplatesTests.cs#L39-L157 .

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/aspire/pull/4816 . Closing this.

**Comment by danmoseley** [comment]
Yeah, my bad for not seeing this (actually we should probably have an owner of this regular chore). Although, there were more updates than in this PR

**Pull request closed without merging**
