### PR TITLE
SchemaStore whitepsace formatting.

### PR DESCRIPTION
**Pull request by mitchdenny**
As part of SchemaStore submission process it does some JSON formatting on the schema. This PR updates the schema file in our repo to match that.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5690)

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]

**Comment by davidfowl** [comment]
This took about 4 days to get in because of manually having to re-run the tests.

**Pull request merged**
