### PR TITLE
Kafka WithDataVolume and WithDataBindMount don't persist messages

### LINKED ISSUE #4909: Kafka WithDataVolume and WithDataBindMount don't persist messages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Calling WithDataVolume or WithDataBindMount on a Kafka resource doesn't persist data across runs of the application. We should ensure we have the right settings set up so the data gets persisted across app runs.

### Expected Behavior

When using WithDataVolume or WithDataBindMount, the messages that are produced should be perserved across app runs. So when the app spins up again, consuming those messages should be possible.

### Steps To Reproduce

Run the following test

```csharp
    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    [RequiresDocker]
    public async Task WithDataShouldPersistStateBetweenUsages(bool useVolume)
    {
        var cts = new CancellationTokenSource(TimeSpan.FromMinutes(3));
        var topic = "test-topic";
        string? volumeName = null;
        string? bindMountPath = null;

        try
        {
            var builder1 = CreateDistributedApplicationBuilder();
            var kafka1 = builder1.AddKafka("kafka");

            if (useVolume)
            {
                // Use a deterministic volume name to prevent them from exhausting the machines if deletion fails
                volumeName = VolumeNameGenerator.CreateVolumeName(kafka1, nameof(WithDataShouldPersistStateBetweenUsages));

                // if the volume already exists (because of a crashing previous run), try to delete it
                DockerUtils.AttemptDeleteDockerVolume(volumeName);
                kafka1.WithDataVolume(volumeName);
            }
            else
            {
                bindMountPath = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
                kafka1.WithDataBindMount(bindMountPath);
            }

            using (var app = builder1.Build())
            {
                await app.StartAsync();
                try
                {
                    var hb = Host.CreateApplicationBuilder();

                    hb.Configuration.AddInMemoryCollection(new Dictionary<string, string?>
                    {
                        [$"ConnectionStrings:{kafka1.Resource.Name}"] = await kafka1.Resource.ConnectionStringExpression.GetValueAsync(default)
                    });

        hb.AddKafkaProducer<string, string>("kafka");

                    using (var host = hb.Build())
                    {
                        await host.StartAsync();

                        var producer = host.Services.GetRequiredService<IProducer<string, string>>();
                        for (var i = 0; i < 10; i++)
                        {
                            await producer.ProduceAsync(topic, new Message<string, string> { Key = "test-key", Value = $"test-value{i}" });
                        }
                    }
                }
                finally
                {
                    // Stops the container, or the Volume/mount would still be in use
                    await app.StopAsync();
                }
            }

            var builder2 = CreateDistributedApplicationBuilder();
            var kafka2 = builder2.AddKafka("kafka");

            if (useVolume)
            {
                kafka2.WithDataVolume(volumeName);
            }
            else
            {
                kafka2.WithDataBindMount(bindMountPath!);
            }

            using (var app = builder2.Build())
            {
                await app.StartAsync();
                try
                {
                    var hb = Host.CreateApplicationBuilder();

                    hb.Configuration.AddInMemoryCollection(new Dictionary<string, string?>
                    {
                        [$"ConnectionStrings:{kafka2.Resource.Name}"] = await kafka2.Resource.ConnectionStringExpression.GetValueAsync(default)
                    });

                    hb.AddKafkaConsumer<string, string>("kafka", consumerBuilder =>
                    {
                        consumerBuilder.Config.GroupId = "aspire-consumer-group";
                        consumerBuilder.Config.AutoOffsetReset = AutoOffsetReset.Earliest;
                    });

                    using (var host = hb.Build())
                    {
                        await host.StartAsync();

                        var consumer = host.Services.GetRequiredService<IConsumer<string, string>>();
                        consumer.Subscribe(topic);
                        for (var i = 0; i < 10; i++)
                        {
                            var result = consumer.Consume(cts.Token);

                            Assert.Equal($"test-key", result.Message.Key);
                            Assert.Equal($"test-value{i}", result.Message.Value);
                        }
                    }
                }
                finally
                {
                    // Stops the container, or the Volume/mount would still be in use
                    await app.StopAsync();
                }
            }
        }
        finally
        {
            if (volumeName is not null)
            {
                DockerUtils.AttemptDeleteDockerVolume(volumeName);
            }

            if (bindMountPath is not null)
            {
                try
                {
                    File.Delete(bindMountPath);
                }
                catch
                {
                    // Don't fail test if we can't clean the temporary folder
                }
            }
        }
    }
```

### Exceptions (if any)

```
  Message: 
Confluent.Kafka.ConsumeException : Subscribed topic not available: test-topic: Broker: Unknown topic or partition

  Stack Trace: 
Consumer`2.Consume(Int32 millisecondsTimeout)
Consumer`2.Consume(CancellationToken cancellationToken)
KafkaFunctionalTests.WithDataShouldPersistStateBetweenUsages(Boolean useVolume) line 169
```

### .NET Version info

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stbau04**
Changes Kafka data directory (unit test mentioned in #4909 still fails but with an other exception - seems as the new data directory is working)
Fixes  #4909
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4947)

### CODE REVIEW

**Comment by eerhardt** [comment]
Can you also enable this test?

https://github.com/dotnet/aspire/blob/8605f40ac701fd711295c4939cd5fa2553bbb593/tests/Aspire.Hosting.Kafka.Tests/KafkaFunctionalTests.cs#L76-L81

**Comment by stbau04** [comment]
Yeah sure, test is updated

**Comment by stbau04** [comment]
The kafka tests are still failing, but with an other exception. @eerhardt should they already work? (There are also exceptions in the Playwright test, but i guess this is not related to the kafka resource?)

**Comment by eerhardt** [comment]
> The kafka tests are still failing, but with an other exception. @eerhardt should they already work? 

If they need to be fixed, can you please fix them? I wasn't able to valdiate them because of this issue. But I followed the same test pattern as used elsewhere.

> (There are also exceptions in the Playwright test, but i guess this is not related to the kafka resource?)

Yeah, this is unrelated flakiness in our tests that we are trying to fix.

**Comment by stbau04** [comment]
@eerhardt There are currently two problems with the resource:
- Volumes/Bind mounts are mounted so that they can only be written by root user - Kafka is run using a different user. The best approach i found for that problem would be to start Kafka as root using (--user root) on the container, but I am not sure whether this has some disadvantages/is a bad practice
- The `await app.StopAsync();` does not actually wait for the container to exit, meaning that the first container still has a lock on the files while the second container is already trying to read - leading to a timeout. The only fix i could currently figure out would be to add a delay before starting the second container (at most with a one minute delay it works). Is there any other way to ensure that the container is shut down?

**Comment by eerhardt** [comment]
>  Is there any other way to ensure that the container is shut down?

We have https://github.com/dotnet/aspire/issues/4878 to try to come up with a solution for that. cc @karolz-ms @mitchdenny 

> Volumes/Bind mounts are mounted so that they can only be written by root user 

You mean the root user inside the container? And Kafka is running as a separate user from the root user, so it can't access the directory?

@karolz-ms @danegsta - thoughts on this scenario? Does DCP support giving access to volumes and mounts to other users?

**Comment by mitchdenny** [comment]
Hrm interesting. Yeah I think we need to solve this. I don't think we should expect the container workloads to change the user they are running as since that seems like a lot of containerized workloads would break if we did that.

How is this solved outside of Aspire when people want to use bindmounts and data volumes. Its not like we are doing anything special here?

**Comment by karolz-ms** [comment]
@stbau04 this is a known issue with bind mounts, in the sense that, depending on what container orchestrator flavor/host OS you use, there might be different steps necessary to ensure that the process running inside the container has permissions to the bind mount https://www.reddit.com/r/docker/comments/1b8dnm6/is_there_an_easy_solution_to_the_permission/

That said there is the host side and the container side, and so you can try to change the user the container is running as (as you tried, running as `root`), or you can try adjust permissions on the folder that you are binding into the container so that the container user has access. Again, steps may differ depending on container orchestrator (Docker and Podman are supported by Aspire) and host OS, but the rule of thumb is that when specifying permissions on the host side, the user ID must match the user ID for the effective user inside the container. Running container as non-root and changing permissions on the host side is considered a safer practice than running as root inside the container. Hope this helps!

**Comment by eerhardt** [comment]
@karolz-ms - do you think we should remove this API until we can make it work? It doesn't sound like there is a straight-forward path to making it work.

**Comment by danegsta** [comment]
One thing to check for Docker volume mounts (both named volumes and bind mounts) is that the behavior can be different depending on whether you're mounting to a path that already exists in a container image or not. If you volume mount to a non-existent folder (even if it's a child of an existing folder), Docker will create the new folder path in the container using root permissions, even if the container itself will run as a non-root user. If the folder already exists, it will preserve the existing permissions inside the container. For bind mounts, it'll also preserve the local file system permissions for any child files/folders that are introduced as part of the mount (named volumes are usually easier to deal with if you don't need to write to/read from files on the host).

**Comment by eerhardt** [comment]
@stbau04 - are you still working on this PR? Can you try the solution above?

**Comment by stbau04** [comment]
@eerhardt Sadly i don't have a lot time at the moment to figure something out. I can give the solution a try but in my opinion it's not a good idea to automatically manipulate the host folder permissions

**Comment by stbau04** [comment]
@eerhardt Seems like changing the directory permission on the host does not work for windows: https://stackoverflow.com/questions/66388158/changing-file-permissions-from-a-mounted-file-from-inside-the-docker-container
So i think there are are basically two possible approaches:
- Run the container as root user (--u root)
- Modify the container image so that chmod is executed (or maybe ensure that the folder already exists with right permissions)

I am soon on holiday for a few weeks, so i am not able to do any more work/research on this topic in the near future

**Comment by eerhardt** [comment]
Thanks for the information and the attempts, @stbau04.

> i am not able to do any more work/research on this topic in the near future

Closing this PR until it can be actively worked on.

**Pull request closed without merging**
