### PR TITLE
Humanize resource state

### LINKED ISSUE #1547: Consider humanizing resource state on dashboard
As mentioned in https://github.com/dotnet/aspire/pull/1517#pullrequestreview-1801412256, we may want to consider humanizing resource states in the resource grid.

### PR DESCRIPTION
**Pull request by adamint**
Calls `Humanize` on the resource state. example (ignore wrong icon type):

image

fixes #1547

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

**Review by JamesNK — APPROVED** [review]
Even easier than I thought it would be.

How come "Failed to start" has a green tick? Was it caused test data? If not, a green tick seems like the wrong icon to show for that state.

**Comment by davidfowl** [comment]
> How come "Failed to start" has a green tick? Was it caused test data? If not, a green tick seems like the wrong icon to show for that state.

I thought we fixed this. https://github.com/dotnet/aspire/issues/1879

**Comment by tlmii** [comment]
He said 

> ignore wrong icon type

I'm assuming he meant that was either test data or from a branch that didn't include the fix.

**Review by tlmii — APPROVED** [review]

**Comment by adamint** [comment]
Yep, I had branched off before that fix was included.

**Pull request merged**
