### PR TITLE
ActiveMQ classic hosting

### PR DESCRIPTION
**Pull request by anoordover**
Please advice on how to proceed with this PR.

Regards Arno Noordover
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4094)

### CODE REVIEW

**Comment by anoordover** [comment]
@dotnet-policy-service agree

**Comment by sebastienros** [comment]
https://activemq.apache.org/

**Comment by JohnGalt1717** [comment]
Any chance we can get this reviewed? Would love to use this ASAP.

**Comment by japj** [comment]
From https://github.com/dotnet/aspire/discussions/6694#discussioncomment-11278840 it looks like this should move into the Aspire CommunityToolkit instead

**Comment by anoordover** [comment]
Merged dotnet/aspire main to this branch.

@davidfowl should I try to migrate this to the CommunityToolkit (see https://github.com/dotnet/aspire/discussions/6694#discussioncomment-11278840)?
Do you have any advice for me migrating this to the CommunityToolkit?

**Comment by anoordover** [comment]
https://github.com/CommunityToolkit/Aspire/issues/253?

**Comment by anoordover** [comment]
Moved this to community: https://github.com/CommunityToolkit/Aspire/pull/273
I will close this PR.
Thank you for your feedback.

**Pull request closed without merging**
