### PR TITLE
Fix triple slash usage of `inheritdoc`.

### PR DESCRIPTION
**Pull request by IEvangelist**
## Description

Many of the container-based hosting integrations include an `internal` tags class, that stores the various container registry, image and tags. Since these members are `internal` the .NET Aspire API docs doesn't expose them in the rendered API docs. Nor are they available to IntelliSense.

For example, see [`RedisBuilderExtensions.AddRedis` Method: Remarks](https://learn.microsoft.com/dotnet/api/aspire.hosting.redisbuilderextensions.addredis?view=dotnet-aspire-9.0#remarks).

To fix this, when we rely on `<inheritdoc />` we must specify the `path` (XPath) to the desired value. Before my change:

image

After my change:

image

This will also fix the .NET Aspire API docs too, the next time we release.

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6718)

### CODE REVIEW

**Comment by eerhardt** [comment]
Can you fix these 2 as well?

https://github.com/dotnet/aspire/blob/c0ff16dff269c0d3409c790e287e54e766ba89d9/src/Aspire.Hosting.Azure.CognitiveServices/AzureOpenAIDeployment.cs#L37-L51

**Comment by eerhardt** [comment]
There are 3 Azure ones that appear to be missed:

https://github.com/dotnet/aspire/blob/c0ff16dff269c0d3409c790e287e54e766ba89d9/src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs#L85

https://github.com/dotnet/aspire/blob/c0ff16dff269c0d3409c790e287e54e766ba89d9/src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs#L109

https://github.com/dotnet/aspire/blob/c0ff16dff269c0d3409c790e287e54e766ba89d9/src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs#L81

(Although, that EventHubs one appears misplaced. It should be on the `RunAsEmulator` method.)

**Comment by sebastienros** [comment]
I recently created a PR that was fixing all these. Didn't we merge release/9.0 back to main? Pretty sure I updated everything to use <remarks> in both the APIs and the tags.

**Comment by sebastienros** [comment]
Yes, that's it, check the release/9.0, it's fine there: https://github.com/dotnet/aspire/blob/release/9.0/src/Aspire.Hosting.Elasticsearch/ElasticsearchContainerImageTags.cs

**Comment by sebastienros** [comment]
release/9.0 is fine, but the PR didn't get merged back correctly apparently (conflicts got resolved using main) https://github.com/dotnet/aspire/pull/6433

**Comment by IEvangelist** [comment]
There might be an issue with the .NET API docs. I'm investigating that and will report back.

**Pull request closed without merging**
