### PR TITLE
Remove RedisInsight AcceptEula API

### PR DESCRIPTION
**Pull request by eerhardt**
We don't want to have a custom license or agreement on our nuget packages. And this API is not ergonomic, so let's not ship this public API until we can ensure this is the way we want to go forever.

Contributes to #5727
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6166)

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

**Review by DamianEdwards — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]

**Comment by eerhardt** [comment]
FYI @Alirexaa

**Pull request merged**
