### PR TITLE
Update Microsoft.Extensions.Http.Resilience to 8.2

### PR DESCRIPTION
**Pull request by eerhardt**
This has a fix for https://github.com/dotnet/extensions/issues/4770 which causes our EndToEnd tests to timeout if a service doesn't start in 100 seconds.

We can update this to the official `8.2.0` when it ships.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2094)

### CODE REVIEW

**Comment by radical** [comment]
and maybe drop the retry from `ProjectInfo.WaitForHealthyStatusAsync` which shouldn't be needed now, and would surface the failure if this breaks.

**Comment by eerhardt** [comment]
> and maybe drop the retry from `ProjectInfo.WaitForHealthyStatusAsync` which shouldn't be needed now, and would surface the failure if this breaks.

It is still needed because the project may return `Unhealthy`, which in that case it needs to retry.

**Comment by radical** [comment]
> > and maybe drop the retry from `ProjectInfo.WaitForHealthyStatusAsync` which shouldn't be needed now, and would surface the failure if this breaks.
> 
> It is still needed because the project may return `Unhealthy`, which in that case it needs to retry.

right, keep missing that. Then no try/catch?

**Comment by eerhardt** [comment]
> Then no try/catch?

That's needed because when it returns `Unhealthy` it also returns a `503` status code. And `HttpClient.GetString` ensures that the status code is a "success". So when it is a 5xx status code an exception gets thrown.

**Review by radical — APPROVED** [review]

**Pull request merged**
