### PR TITLE
Add stress playground

### PR DESCRIPTION
**Pull request by JamesNK**
A place to stress the dashboard with large and strange data.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2600)

### CODE REVIEW

**Comment by kvenkatrajan** [comment]
This is great - thanks @JamesNK  - just curious did the logs stress test yield anything we need to fix from a page rendering perspective?

**Comment by JamesNK** [comment]
Console logs, yes - https://github.com/dotnet/aspire/issues/2507

Telemetry logs, no

**Comment by JamesNK** [comment]
Could someone please review this.

**Review by davidfowl — APPROVED** [review]

**Comment by davidfowl** [comment]
The launch profile change got caught in here 😄

**Pull request merged**
