### PR TITLE
Update .NET 9 SDK and consume Functions RunCommand changes

### PR DESCRIPTION
**Pull request by captainsafia**
## Description

Upgrade to a .NET 9 RC 2 SDK and 2.0.0-preview1 builds of Azure Functions so that we can consume the `DotnetRunCommand` changes and remove our workaround from the code.

## Checklist

- Is this feature complete?
  - [X] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [X] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [X] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5905)

### CODE REVIEW

**Comment by eerhardt** [comment]
The tests appear to be failing:

```
Exception Message
System.Threading.Tasks.TaskCanceledException : Task was canceled before these messages were found: 'MyAzureBlobTrigger: blobTrigger'
---- System.Threading.Tasks.TaskCanceledException : A task was canceled.
CallStack
   at Aspire.Hosting.Tests.Utils.LoggerNotificationExtensions.WaitForAllTextAsync(DistributedApplication app, IEnumerable`1 logTexts, String resourceName, CancellationToken cancellationToken) in /datadisks/disk1/work/B4A60997/w/B42E099B/e/tests/Aspire.Playground.Tests/LoggerNotificationExtensions.cs:line 108
   at Aspire.Playground.Tests.ProjectSpecificTests.AzureFunctionsTest() in /datadisks/disk1/work/B4A60997/w/B42E099B/e/tests/Aspire.Playground.Tests/ProjectSpecificTests.cs:line 72
   at Aspire.Playground.Tests.ProjectSpecificTests.AzureFunctionsTest() in /datadisks/disk1/work/B4A60997/w/B42E099B/e/tests/Aspire.Playground.Tests/ProjectSpecificTests.cs:line 130
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Aspire.Hosting.Tests.Utils.LoggerNotificationExtensions.WaitForAllTextAsync(DistributedApplication app, IEnumerable`1 logTexts, String resourceName, CancellationToken cancellationToken) in /datadisks/disk1/work/B4A60997/w/B42E099B/e/tests/Aspire.Playground.Tests/LoggerNotificationExtensions.cs:line 92
```

**Comment by captainsafia** [comment]
> The tests appear to be failing:

Yeah, I can't repro it reliably locally or in CI so it's a bit tricky to debug. The stack trace that I did see seemed to indicate that it was a result of the Functions host not launching (e.g. you get the issue about gRPC not being able to connect).

This might indicate that the `RunCommand` that launches the Functions host from the worker SDK wasn't actually invoked but this needs more debugging 🤔

**Comment by eerhardt** [comment]
Looks like the test is still failing.

**Comment by captainsafia** [comment]
> Looks like the test is still failing.

Yeah, I haven't poked at this any further since we last chatted. I'll planning to revisit once all the other inflight things land. In the meantime, I'll move this to draft mode.

**Comment by captainsafia** [comment]
Closing this until we have the finalized bits from Functions.

**Pull request closed without merging**
