### PR TITLE
Fix: Project Names with Spaces Break the Build

### LINKED ISSUE #945: Project Names with Spaces Break the Build
If you name your project something like "Test Aspire", and make no other changes to the Aspire Starter Project, and then build, it will break the build, as the generated code has spaces in it:

image

Either you shouldn't allow spaces in project names at creation, or your code generation needs to replace all spaces with underscores, like it does for periods.

image

image

image

I am running on Windows 11.

### PR DESCRIPTION
**Pull request by kiapanahi**
Fixes: #945.

I however couldn't find a solution for projects with (.) in their names.
I've figured out that the generated `IServiceMetadata` is correct but the actual _name-of-project_`.AppHost` template is outputting faulty template.

### CODE REVIEW

**Comment by DamianEdwards** [comment]
The issue when using a `.` in the project name seems like a regression from https://github.com/dotnet/aspire/pull/510 but I'm not sure what's causing it. We might need help from the template engine folks because the [name form we're using](https://github.com/dotnet/templating/wiki/Naming-and-default-value-forms) now **should** be indicating that we want the class form.

That said, you could try changing [`"sourceName": "AspireStarterApplication-1"`](https://github.com/dotnet/aspire/blob/main/src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json#L18) to `"sourceName": "AspireStarterApplication.1"` and then change the [reference to it in Program.cs](https://github.com/dotnet/aspire/blob/main/src/Aspire.ProjectTemplates/templates/aspire-starter/AspireStarterApplication-1.AppHost/Program.cs#L7) to `Projects.AspireStarterApplication__1_ApiService`

**Comment by kiapanahi** [comment]
@DamianEdwards 

Thank you for the pointers.
I'd love for you to take a look at the updated templates.

**Comment by DamianEdwards** [comment]
@kiapanahi have you tested the templates locally? After calling `build.cmd -pack` in the repo root, you should have a package like `./artifacts/packages/Release/Shipping/Aspire.ProjectTemplates.8.0.0-dev.nupkg` that has the templates in it. You can install that locally by first deleting your template cache (`~/.templateengine/packages` directory and `~/.templateengine/packages.json`) and then calling `dotnet new -i <path-to-package.nupkg>`. Then you can create some projects using your updated templates and verify the relevant scenarios (name with `.` in it, name with spaces in it, etc.).

**Comment by DamianEdwards** [comment]
> I think I know how to test it though. I I'm not wrong, I need to somehow reference my own build of Aspire.Hosting package instead of the !!REPLACE_WITH_LATEST_VERSION!! one which still contains the whitespace bug.

You'll need to create a local NuGet feed that points at the artifacts directory of the repo (`./artifacts/packages/Release/Shipping/`). Then you can reference the `-dev` suffixed version which is what you built.

**Comment by kiapanahi** [comment]
Alright, I managed to test with the locally built `-dev` NuGet packages and I can confirm that the issue with the replacing of whitespace with underline is fixed.

**Review by DamianEdwards — APPROVED** [review]
Thanks for this!

**Comment by kiapanahi** [comment]
Thank you for all of your pointers and helps

**Pull request merged**
