### PR TITLE
Correct XML Docs for `RabbitMqServerResource.PrimaryEndpoint`

### PR DESCRIPTION
**Pull request by afscrome**
It's a RabbitMQ server, not redis 😉.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4118)

### CODE REVIEW

**Comment by danmoseley** [comment]
thanks. there's a bunch of copy/pastes of "Gets the primary endpoint for the Redis server." .. can you fix others as needed?

**Comment by timheuer** [comment]
Also see one for PostgreSQL as a copy/paste typo as well here.

**Comment by afscrome** [comment]
Yea, there are a few - https://github.com/search?q=repo%3Adotnet%2Faspire%20%22Gets%20the%20primary%20endpoint%20for%20the%20Redis%20server%22&type=code .  

I can have a look but it may not be until the weekend.  If you want to merge this PR in it's current form feel frere and I'll follow up with a second PR.  Otherwise I'll append to this one.

**Review by danmoseley — APPROVED** [review]

**Review by eerhardt — APPROVED** [review]

**Comment by danmoseley** [comment]
@afscrome ironically our edits made this large enough we need you to agree to the CLA . Could you do that? You'd probably have needed to do it for the next PR anyway. You only need to do it once.

**Comment by afscrome** [comment]
One of my collogues has already signed the CLA for our company - https://github.com/dotnet/sign/pull/656#issuecomment-1957227841 .  Do I need to do something to link my account to the company or do I need to agree again.

**Comment by danmoseley** [comment]
I believe the bot requires it from every account. But only once each

**Comment by danmoseley** [comment]
Note you just have to leave the indicated comment right here in this PR thread

**Comment by afscrome** [comment]
@dotnet-policy-service agree company="Trayport"

**Pull request merged**
