### PR TITLE
Setting minimum TLS to 1.2 by default

### LINKED ISSUE #4692: Azure Storage should provision with TLS 1.2 by default
When deploying an Azure Storage resource with Aspire, it will default to deploying with TLS 1.0, which results in an S360 violation internally, but also is against the general recommended security practices.

TLS 1.0 and 1.1 will be removed [on 1 November 2024](https://techcommunity.microsoft.com/t5/azure-storage-blog/tls-1-0-and-1-1-support-will-be-removed-for-new-amp-existing/ba-p/4026181), so enforcing TLS 1.2 now will ensure that resources are deployed correctly and won't hit any issues.

### PR DESCRIPTION
**Pull request by aaronpowell**
Fixes #4692

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4695)

### CODE REVIEW

**Comment by mitchdenny** [comment]
LGTM

**Review by mitchdenny — APPROVED** [review]

**Comment by danmoseley** [comment]
This code coverage change is on all PR's. Some other change reduced it? Merging.

**Comment by danmoseley** [comment]
thanks @aaronpowell

**Pull request merged**
