### PR TITLE
Rename 'samples' to 'playground'

### LINKED ISSUE #1682: The "samples" folder does not contain samples from a user-perspective
Our samples folder contains what appear to be apps for .NET Aspire users to reference, where in fact they're intended more as integration tests for developers of this repo.

They're not great examples for users to reference, as we do things in these projects that we don't expect users to do. For example, in #1667 we have the app host projects reference the dashboard project directly.

We should rename the `samples` folder, or move its children somewhere else to avoid this confusion. 

Actual user samples are located in https://github.com/dotnet/aspire-samples

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #1682

To avoid potential confusion, we rename this folder. These are not good samples for users to refer to as an example of how to build .NET Aspire applications. There's non-standard stuff in these projects to support development within this repo.

Also add a README.md file in that folder to direct people to the sample repo.

If this change is merged, developers of this repo will need to re-select their startup project.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1689)

### CODE REVIEW

**Comment by mitchdenny** [comment]
What was the consensus here from the conversations we had this week? I thought we were going to keep samples as is but stop using it as a playground for trying things out. I've actually put up another PR which adds a `src/Playgrounds` folder for some Cosmos experimentation I'm doing.

#1697

**Comment by mitchdenny** [comment]
Note, I don't have a strong opinion on `integration` vs `playgrounds`. I just want to make sure that we were moving the samples/eshoplite sample (which is more sample-like rather than a more focused driver project).

**Comment by drewnoakes** [comment]
eShopLite, dapr and orleans are all going to need code that's specific to this repo, which should not be copy/pasted into user projects.

The differences will be in the app hosts. In the projects being moved here, they'll:

- Suppress the default dashboard.
- Register this repo's dashboard project as a resource.

As mentioned on Teams, we'll need the app model ordering changes to respect both the workload executable, and also the project resource, so that this mechanism works, allowing us to test with real integration test suites, with only a few modifications to make them work.

**Comment by eerhardt** [comment]
I think I'd rather use the term "test" somewhere in this name. "TestProjects" or "TestApps". If you really want to use "Integration", I could be OK with "IntegrationTestApps", but I think just "integrations" isn't descriptive enough.

**Comment by DamianEdwards** [comment]
My 2c: I like simply renaming it to "integrations" or "playground". I think using "test" just isn't correct in this case as we have actual tests in the "tests" directory.

**Comment by davidfowl** [comment]
I like playground

**Comment by eerhardt** [comment]
The thinking is that we would never write automated tests against these projects? CI would make sure they build, but we wouldn't ensure they don't break in other ways? And if we wanted an automated test, we would either move or duplicate the project into `tests\testproject`?

**Comment by davidfowl** [comment]
Thats right @eerhardt

**Comment by drewnoakes** [comment]
Renamed `integrations` to `playground` and fixed merge conflicts.

**Review by danmoseley — APPROVED** [review]

**Pull request merged**
