### PR TITLE
Throw from GetEndpoint if endpoint doesn't exist

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes the original part of https://github.com/dotnet/aspire/issues/609
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1880)

### CODE REVIEW

**Comment by davidfowl** [comment]
This can't happen early because for projects, the launch profile URLs are injected [later in the pipeline](https://github.com/dotnet/aspire/blob/677511afd2b185acf1d1ec3ed5ed50547501bff0/src/Aspire.Hosting/Dcp/DcpDistributedApplicationLifecycleHook.cs#L33)

**Comment by BrennanConroy** [comment]
Ugh

**Comment by davidfowl** [comment]
OR maybe we delete this hook and do it earlier (on project resource creation).

**Comment by BrennanConroy** [comment]
Wait, that hook doesn't add a named endpoint, so it wouldn't even be gettable from `GetEndpoint`

**Comment by davidfowl** [comment]
The scheme becomes the name if there's no name.

**Comment by BrennanConroy** [comment]
> OR maybe we delete this hook and do it earlier (on project resource creation).

That seems difficult since the endpoint can change based on `LaunchProfileAnnotation` which might not be set before calling `GetEndpoint`.

**Comment by davidfowl** [comment]
What should we do here?

**Comment by davidfowl** [comment]
I'm gonna close this as fixed already, I made [this change](https://github.com/dotnet/aspire/blob/1f8e53ddd36a0f03c6fdfb9b5bfc8e7810178905/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs#L37) during refactoring and it defers the check until access. Not as good as throwing up front but that has issues.

**Pull request closed without merging**
