### PR TITLE
Fixing unintended formatting changes

### LINKED ISSUE #5436: [WebToolsE2E][Aspire] After creating an Aspire project, some warning icons are displayed in Dependencies | Projects of the AppHost project.
**REGRESSION INFO**: Worked in Aspire 8.1.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.401
3. Install VSCode or VS
4. Install Aspire 8.2.0-preview.1.24424.2

**REPRO STEPS**

1. Open CMD, create an Aspire Starter App using following commands:
`dotnet new aspire-starter -o AspireStarterApp`
2. Open this project using VSCode or VS.

**ACTUAL**
Dependencies | Projects show warning icon. No warnings in Error List.
image
image

**EXPECTED**
No warning icon.

### PR DESCRIPTION
**Pull request by joperezr**
## Description

When making the workload changes, I ran the xml formatter on the SDK.targets file to format tabs/spaces and indentation correctly, but it looks like that made some formatting changes that introduced bugs like adding newlines to property values, which would then break conditions when doing string comparisons. Thanks a lot @eerhardt for debugging and finding this out. The changes in this PR revert all the formatting changes made in that PR, which means the net difference since 8.1 will be the addition of the new target.

Fixes #5436 

## Checklist

- Is this feature complete?
  - [ ] Yes. Ready to ship.
  - [x] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5471)

### CODE REVIEW

**Comment by joperezr** [comment]
After applying the changes in this PR locally, I can see that the issue is resolved:

image

**Review by eerhardt — APPROVED** [review]
LGTM. Thanks for fixing this!

**Comment by v-elenafeng** [comment]
@joperezr Is this ready to be merged? We're still experiencing the issue with 9.0 P4.

**Pull request merged**
