### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by eerhardt**
- Remove unnecessary folders in .csprojs
- Remove PasswordUtil since it is not used by product code.
- Delete tests that aren't testing Aspire code
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2849)

### CODE REVIEW

**Comment by davidfowl** [comment]
I think we need password util to be used in the password generation but I’m not sure.

**Comment by eerhardt** [comment]
> I think we need password util to be used in the password generation but I’m not sure.

All it does today is replace `"` with `""`, which the password generation never generates `"` today.

Also, this method/class isn't good enough. Reading https://stackoverflow.com/questions/61486081/password-with-special-characters-in-connectionstring, you need to add single quotes around the password if you are using `;`, for SqlServer connection strings. Other string formats have different rules - for example RabbitMQ puts the password in a System.Uri, which needs a lot more escaping.

And as stated above, nothing is actually using it.

These are the reasons I'm deleting it for now. It isn't doing what we think it is.

**Comment by davidfowl** [comment]
Good to know, nuke it 😅

**Comment by eerhardt** [comment]
For password generation specifically, if we find the need to customize the "special characters", we can add a new option `overrideSpecial` which allows the resource to specify exactly which special characters can be used. See https://github.com/Azure/azure-dev/issues/3462. (Note we don't have this option today, but we can add it once we find the need.)

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
