### PR TITLE
View details with row click

### PR DESCRIPTION
**Pull request by JamesNK**
Use new OnRowClick feature in FluentUI to show details on pages:

* Resources
* Structured logs
* Traces
* Trace detail (already had row click, moves feature to row instead of cell)

Clickable UI on rows takes precedent. For example, clicking on a resource endpoint URL will launch a new browser to that URL. It doesn't open the detail view.

Changes:

* Add OnRowClick to data grids
* Add `@onclick:stopPropagation="true"` where required. Clicking on UI will bubble the event up until it stops. That means clicking on the `View` button triggers the button action and the row click action. The fix is to tell Blazor to stop propagating the event with the `stopPropagation` attribute.
* Re-enable pointer on grids with row click events

Demo:
row-click

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5000)

### CODE REVIEW

**Comment by ilmax** [comment]
Was wondering if it make sense to dismiss the details when pressing the Esc key.

**Comment by drewnoakes** [comment]
> Was wondering if it make sense to dismiss the details when pressing the Esc key.

I think so. Perhaps clicking the resource a second time hides the details too.

**Comment by JamesNK** [comment]
ESC closing the details view isn't relevant to this PR. Please create a separate issue.

**Comment by drewnoakes** [comment]
I see the relevance being that it's now much easier to accidentally open the details pane by clicking in the grid. It's friendly to have escape get things back to "normal".

**Comment by JamesNK** [comment]
They're conceptually related, but this PR is focused on row clicks. If closing with ESC is done, it will be in a different PR.

**Comment by JamesNK** [comment]
Issue for shortcut to close details view: https://github.com/dotnet/aspire/issues/5050

**Comment by JamesNK** [comment]
@leslierichardson95 Do you have any feedback on this UI change?

**Review by leslierichardson95 — COMMENTED** [review]
This change looks good to me! :)

**Review by adamint — APPROVED** [review]

**Comment by samsp-msft** [comment]
Love the interaction this enables 😸

**Pull request merged**
