### PR TITLE
make policheck nearly clean

### PR DESCRIPTION
**Pull request by danmoseley**
* plotly is full of geopolitical terms that are assumed fine in context and it's not something we control anyway
* country and capital are fine in context so removed them where they were arbitrary strings
* tested locally with policheck.exe.

this makes us 98% clean which makes it easy to eyeball violations.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4992)

### CODE REVIEW

**Comment by danmoseley** [comment]
@julioct also a different scanner detected the secret added in your change. I am excluding it as hopefully it is not in fact a secret...

**Comment by danmoseley** [comment]
Latest plotly is actually 2.34 .. maybe we need a readme next to it to say "update policheck xml when you update plotly version"

**Comment by julioct** [comment]
> @julioct also a different scanner detected the secret added in your change. I am excluding it as hopefully it is not in fact a secret...

It was a password for a test user used in the Keycloak playground. It was already removed in [this commit](https://github.com/dotnet/aspire/commit/ffb5d9d7dfc410dd6ee0db18594e459faea65a7b)

**Comment by danmoseley** [comment]
Great, reverted that commit

**Review by eerhardt — APPROVED** [review]

**Comment by danmoseley** [comment]
@JamesNK @adamint note this file needs an update when getting a new plotly.

**Comment by JamesNK** [comment]
> Latest plotly is actually 2.34 .. maybe we need a readme next to it to say "update policheck xml when you update plotly version"

Are wildcards supported? e.g.

```xml
<Exclusion Type="FileName">plotly-*.js</Exclusion>
```

**Comment by danmoseley** [comment]
No mention in the doc linked, but I should have confirmed by trying it..

**Pull request merged**
