### PR TITLE
WaitFor for RabbitMQ

### PR DESCRIPTION
**Pull request by mitchdenny**
## Description

Adds `WaitFor` support for RabbitMQ

Related: #5645

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5718)

### CODE REVIEW

**Comment by davidfowl** [comment]
We gotta disable this repository test. It’s failing all of the PRs

cc @JamesNK @radical

**Comment by JamesNK** [comment]
@radical How can I view the log output for this test?

**Comment by davidfowl** [comment]
I couldn’t find the logs for that test

**Comment by JamesNK** [comment]
Me neither. The test is setup to write output: https://github.com/dotnet/aspire/pull/5701

And I can see test output locally:

image

**Comment by davidfowl** [comment]
Lets disable it and file an issue, I'd like to unblock these PRs.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
