### PR TITLE
Make status column consistent by moving resource error icons to a separate column 

### LINKED ISSUE #1534: Status column consistency
_Originally from https://github.com/dotnet/aspire/pull/1378#issuecomment-1874297272_

Can we look to align the text where icons are displayed on the right with that of the text where icons are not displayed. Currently looks a bit staggered in the display. Also the Running status with display of (3) is much larger than the icons displayed on the left. Can it be made the same size as the error and warning icons?

### PR DESCRIPTION
**Pull request by adamint**
As pointed out, the status column doesn't look very consistent.

As suggested by @kvenkatrajan, 
- I've extracted resource error appearance into a separate, sortable, conditional column named Errors that only appears when any resource has an error.
- Each error is shown as a) a button, if there are no error logs, or b) a CounterBadge + button if there are
- Clicking on a button will take you to the relevant structured logs page for the resource

image

Resolves #1534 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1538)

### CODE REVIEW

**Comment by davidfowl** [comment]
Why is there a box around those icons?

**Comment by adamint** [comment]
Because they are buttons 🙂

**Comment by davidfowl** [comment]
It doesn't look great... I'm not sure we want to burn real estate on the error column either.

**Comment by adamint** [comment]
I'm open to suggestions on styling.

> I'm not sure we want to burn real estate on the error column either.

This column only appears when there are any errors.

**Comment by kvenkatrajan** [comment]
Can we reduce the size of the column to the width of the icon? And maybe just have the column itself as an alert icon (that would reduce the real estate width on it) similar to this
image

Also @adamint  this column is sortable correct? This would allow for quick glance of errors/warnings.

@davidfowl  the earlier display appeared staggered and the icons were a mix of right alignment (Running error logs) and left alignment (Exited/finished warnings): 
https://private-user-images.githubusercontent.com/20359921/292006514-7e6eff57-401d-4f8a-a69f-3bd514b7a365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTM3NDcsIm5iZiI6MTcwNDMxMzQ0NywicGF0aCI6Ii8yMDM1OTkyMS8yOTIwMDY1MTQtN2U2ZWZmNTctNDAxZC00ZjhhLWE2OWYtM2JkNTE0YjdhMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwMjQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MGJiNTMxODQ5NzczMjEzNzAyZGY0ZjBiOWMyYjhiOTliOGM2YjY5N2VlZWEyNTcyZDg2MzIzMjU5OWY0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hyBo-CfCfH_2AZ_Tr2qJbewLKqwkt8aK3Psxkl2R97Q

We can always run this by the UX board for their input as well. CC: @leslierichardson95

**Comment by tlmii** [comment]
What if we were to:

1. Keep the merged icons (or something similar) that Adam has above)
2. Keep it in the status column
3. Put it on the left of the text, and 
4. Add an appropriate margin to statuses without an icon (with all the appropriate conditionals that it only needs to be there if _some_ status has an icon, similar to the logic around showing the column now). 

That would preserve some screen real estate and fix the staggered alignment that led to this discussion. You'd lose the sortability but I'm not sure sorting by that error status would be immediate obvious to most people anyway.

If it were me, I'd also use the stealth appearance for the button, but that's a secondary discussion I think.

**Comment by JamesNK** [comment]
I think the error icons should stay as they are (in the state column) and add icons for non-error states (a green tick for running, a gray something for starting, etc).

If every resource has an icon, then that fixes the alignment issue.

**Comment by adamint** [comment]
@tlmii I'll mock that up.

@JamesNK, would you be worried that the column might be too noisy if every column has an icon?

**Comment by JamesNK** [comment]
image

I think it looks ok.

**Pull request closed without merging**
