### PR TITLE
Only build manifest when building in VMR in general (#2141)

### PR DESCRIPTION
**Pull request by mmitche**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2268)

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
You will need an approval from @joperezr. I don't have permissions here.

**Comment by joperezr** [comment]
This change was done in main already, right? If so, it will flow into vNext automatically when https://github.com/dotnet/aspire/pull/2168 gets merged. If this is urgent, then I'm fine to take it, but if not, I'd rather opt to wait for the merge from main to happen so as to avoid merge conflicts.

**Comment by mmitche** [comment]
> This change was done in main already, right? If so, it will flow into vNext automatically when #2168 gets merged. If this is urgent, then I'm fine to take it, but if not, I'd rather opt to wait for the merge from main to happen so as to avoid merge conflicts.

Fine to wait.

**Comment by joperezr** [comment]
Sounds good, I'll close this one then, and will prioritize #2168 and try to get that merged today.

**Comment by joperezr** [comment]
Just to close on this, PR 2168 was merged to vNext, so the change is in now.

**Pull request closed without merging**
