### PR TITLE
Remove dotnet8 feed comment

### PR DESCRIPTION
**Pull request by eerhardt**
This is no longer needed.

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]

**Comment by eerhardt** [comment]
> error NU1102: Unable to find package Microsoft.Extensions.Http.Resilience with version (>= 8.1.0-preview.23565.2) [D:\a\_work\1\s\.dotnet\sdk\8.0.100\NuGet.targets]

Hmm, this built on my machine, but I had the package already cached. I guess this feed is needed.

This error does touch on the servicing conversation though. Are we guaranteed that `Microsoft.Extensions.Http.Resilience` version `8.1.0` will ship on nuget.org before we ship our preview2? cc @joperezr

**Comment by joperezr** [comment]
> This error does touch on the servicing conversation though. Are we guaranteed that Microsoft.Extensions.Http.Resilience version 8.1.0 will ship on nuget.org before we ship our preview2? cc @joperezr

The current plan is to ship 8.1.0  Jan 9th.

**Comment by eerhardt** [comment]
> > This error does touch on the servicing conversation though. Are we guaranteed that Microsoft.Extensions.Http.Resilience version 8.1.0 will ship on nuget.org before we ship our preview2? cc @joperezr
> 
> The current plan is to ship 8.1.0 Jan 9th.

Sounds like we will need to back out updating this reference then.

**Comment by danmoseley** [comment]
merging as certainly the comment is not relevant any more.

**Comment by eerhardt** [comment]
> > > This error does touch on the servicing conversation though. Are we guaranteed that Microsoft.Extensions.Http.Resilience version 8.1.0 will ship on nuget.org before we ship our preview2? cc @joperezr
> > 
> > 
> > The current plan is to ship 8.1.0 Jan 9th.
> 
> Sounds like we will need to back out updating this reference then.

I've opened #942 for this.

**Pull request merged**
