### PR TITLE
style: change finished ressource icon to success

### PR DESCRIPTION
**Pull request by pierrebelin**
Related to #4127

Change finished executable succeed icon from warning to checkmark
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4365)

### CODE REVIEW

**Review by adamint — APPROVED** [review]

**Review by drewnoakes — APPROVED** [review]
Thanks very much!

**Comment by davidfowl** [comment]
I think this broke "Failed to start" with a null exit code:

image

**Comment by davidfowl** [comment]
Filed an issue here https://github.com/dotnet/aspire/issues/4498

**Comment by pierrebelin** [comment]
@adamint It's totally mine, I didn't check this case. Do you want me to fix it?

**Comment by mitchdenny** [comment]
@pierrebelin PR is most welcome :)

**Pull request merged**
