### PR TITLE
Change traces page duration progress bar to a ring icon

### LINKED ISSUE #689: Contrast issues in duration bar on /Traces
The contrast between the standard background and the duration bars on the /Traces page doesn't meet the normal minimum contrast requirements for user interface elements in either mode:

Dark Mode:
image
Light mode:
image

Additionally, the contrast between the subtext and the duration highlight color doesn't meet the minimum contrast requirements. This part is additionally complicated because we don't know whether the subtext is over, partially over, or not over the duration bar, and that occurrence changes as the user resizes the page and the columns:
image

A few things we need to do here:

1.  It may not be possible to pick a color for the color bars that has sufficient contrast with the background AND sufficient contrast with the foreground. But we may be able to ignore the contrast issue with the background if we are conveying the same information in another way on the page. We should see what other ways we could convey that information (I believe it is basically a ratio of the current row's duration to the longest duration) on the page and talk to the a11y folks to see if that is sufficient.
2. Even if we do the above, we'd still need to make sure that the text contrast with the duration background is sufficient.

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspire/issues/689

a11y requirements make the trace progress bar problematic. A potential replacement is to replace the progress bar with an icon.

Looks pretty good to me. Hopefully no a11y issues? 🙏 Has a benefit of being in the duration column so it's obvious what it's for. Some people either didn't notice the progress bar or didn't know what it meant.

Screenshot:
image

Thoughts?

The PR code is hacky. If we like this then I'll clean it up.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1387)

### CODE REVIEW

**Comment by adamint** [comment]
Why is the FluentProgressRing component not being used? I would strongly suggest using it.

Overall, I do like this idea

fyi: you can do a quick accessibility pass using Accessibility Insights for web

**Comment by JamesNK** [comment]
> Why is the FluentProgressRing component not being used? I would strongly suggest using it.

It doesn't have a way to change the stroke width, i.e. the thickness of the circle. It doesn't look good when it is a small size.

And it doesn't support completing the remainder of the circle with another color. Many rows have a small dot of purple which doesn't make sense.

image

**Comment by adamint** [comment]
@vnbaaij are these improvements possible? I see these properties are configurable in other fluent ui wrappers

**Review by adamint — APPROVED** [review]
Could you double check that this passes Accessibility Insights check? I wonder if the svg needs labeling

**Comment by tlmii** [comment]
We can style most of the FluentProgressRing ourselves as is. This is with the FluentProgressRing and just giving a color to the rest of the ring. I didn't change the stroke width. I think it looks ok. 

image
image

**Comment by JamesNK** [comment]
Better. I think it looks better with a thicker line.

How about sticking with custom SVG for now, and if Fluent UI adds an option in the future for changing the stroke width, then we switch to `FluentProgressRing`?

**Comment by JamesNK** [comment]
Created a feature request for the FluentUI folks: https://github.com/microsoft/fluentui-blazor/issues/1113

**Comment by tlmii** [comment]
We can get close to what you've got with just CSS. It's a little chunkier than yours because we can't change the viewbox, but this is 4px stroke width like yours:

image
image

```css
::deep fluent-progress-ring::part(background) {
    stroke: var(--neutral-fill-input-alt-active);
    stroke-width: 4px;
    r: 6px;
}

::deep fluent-progress-ring::part(determinate) {
    stroke-width: 4px;
    r: 6px;
}
```

We do get a bunch of aria attributes with the FluentProgressRing that'll be helpful for accessibility... just need to add a title attribute and it'll pass, I think. But I'm fine either way. Just trying to provide options.

**Comment by JamesNK** [comment]
Updated to use progress ring control.

**Comment by dvoituron** [comment]
> We can get close to what you've got with just CSS. It's a little chunkier than yours because we can't change the viewbox, but this is 4px stroke width like yours:

This CSS seems correct, but the `Value` no longer corresponds to the result. For example, 50% no longer displays progress at 50% 😀 You need to add `stroke-dashoffset`.

**Comment by JamesNK** [comment]
Thanks, I see it's definitely off when I hardcode 25%, 50% and 75% values.

I don't think there is a constant `stroke-dashoffset` that works for all values. It is either too big or too small at 25% and 75%. Lower-level support is needed in the control.

**Comment by dvoituron** [comment]
In deed, I'm looking into the possibility of adding a `FluentprogressRing.Stroke` property, which would be an enumeration of the "normal", " large", " thin" type. This would simplify management of this value.

**Comment by dvoituron** [comment]
See https://github.com/microsoft/fluentui-blazor/issues/1113#issuecomment-1855902727
FluentProgressRing

**Comment by dvoituron** [comment]
Will be included in the next release of FluentUI.Blazor lib.
See PR https://github.com/microsoft/fluentui-blazor/pull/1121

**Pull request merged**
