### PR TITLE
add markdown lint

### PR DESCRIPTION
**Pull request by danmoseley**
to avoid any future broken links.

### CODE REVIEW

**Comment by danmoseley** [comment]
I've verified that bad markdown does break the build.

One note in case it's useful to anyone -- the markdownlint extension in VS Code does not work well for me: I can't get it to respect the configuration files, so it flags things I've suppressed in files I've marked to ignore. Instead, to run markdownlint locally I did
```sh
npm install -g markdownlint-cli
markdownlint -c .markdownlint.json "**/*.md"
```
and this seems to match what happens in CI.

**Comment by danmoseley** [comment]
build broken
```
##[error]samples\dapr\AppHost\DaprAppHost.csproj(0,0): error NU1605: (NETCORE_ENGINEERING_TELEMETRY=Restore) Warning As Error: Detected package downgrade: Microsoft.Extensions.ObjectPool from 8.0.0 to 8.0.0-rtm.23524.15. Reference the package directly from the project to select a different version. 

```

**Comment by danmoseley** [comment]
https://www.nuget.org/packages/Microsoft.Extensions.ObjectPool/8.0.0 does exist...

**Comment by danmoseley** [comment]
we can presumably remove this too
```xml
    <!-- Required as https://github.com/dotnet/runtime/pull/89509 did not get backported to .NET 8 Preview 7 -->
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
```

**Review by joperezr — APPROVED** [review]
:shipit:

**Comment by joperezr** [comment]
Not sure why it's not showing here, but PR has passed now: https://dev.azure.com/dnceng-public/public/_build/results?buildId=469639&view=results. Manually merging.

**Pull request merged**
