### PR TITLE
Suppress dashboard resource client error on shutdown

### LINKED ISSUE #6253: Suppress DashboardClient errors in apphost
Saw this on apphost shutdown.

```
fail: Aspire.Hosting.Dashboard.Model.DashboardClient[0]
      Error loading data from the resource service.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Grpc.Net.Client.Internal.Retry.RetryCallBaseClientStreamReader`2.MoveNext(CancellationToken cancellationToken)
         at Grpc.Core.AsyncStreamReaderExtensions.ReadAllAsyncCore[T](IAsyncStreamReader`1 streamReader, CancellationToken cancellationToken)+MoveNext()
         at Grpc.Core.AsyncStreamReaderExtensions.ReadAllAsyncCore[T](IAsyncStreamReader`1 streamReader, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Aspire.Dashboard.Model.DashboardClient.<>c__DisplayClass29_1.<<EnsureInitialized>g__WatchResourcesAsync|5>d.MoveNext() in /_/src/Aspire.Dashboard/ResourceService/DashboardClient.cs:line 323
      --- End of stack trace from previous location ---
         at Aspire.Dashboard.Model.DashboardClient.<>c__DisplayClass29_1.<<EnsureInitialized>g__WatchResourcesAsync|5>d.MoveNext() in /_/src/Aspire.Dashboard/ResourceService/DashboardClient.cs:line 323
      --- End of stack trace from previous location ---
         at Aspire.Dashboard.Model.DashboardClient.<>c__DisplayClass29_0.<<EnsureInitialized>g__WatchResourcesWithRecoveryAsync|3>d.MoveNext() in /_/src/Aspire.Dashboard/ResourceService/DashboardClient.cs:line 298
      --- End of stack trace from previous location ---
         at Aspire.Dashboard.Model.DashboardClient.<EnsureInitialized>g__ConnectAndWatchResourcesAsync|29_1(CancellationToken cancellationToken) in /_/src/Aspire.Dashboard/ResourceService/DashboardClient.cs:line 246

C:\Users\davifowl\source\repos\AppHost46\AppHost46\bin\Debug\net8.0\AppHost46.exe (process 21048) exited with code 0 (0x0).
```

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

The app host stops the dashboard service before the dashboard. That causes the dashboard to report it has an error getting data from the app host when it is stopped with CTRL+C.

Logging the error is valid. From the dashboard's perspective the server just died. It isn't appropriate to completely suppress this error.

The fix in this PR is to stop listening to dashboard logs earlier. Rather than waiting for the lifecycle hook to be disposed, the app host stops listening when the app host begins stopping. The dashboard still logs the error, but the app host is no longer listening.

Fixes https://github.com/dotnet/aspire/issues/6253

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6315)

### CODE REVIEW

**Review by mitchdenny — APPROVED** [review]
LGTM - test failures need investigation to confirm they aren't related to this change though - but didn't want to block once you figure that out.

**Comment by davidfowl** [comment]
Are you sure this runs before the server stops listening?

**Comment by JamesNK** [comment]
I tested with breakpoints placed in the app.

Operatons:
1. App host stopping
2. `DashboardServiceHost` stopping
3. The `WebApplication` inside the host stopping
4. The watch resources method is listening to `IHostApplicationLifetime.ApplicationStopping` and aborts. This is required because otherwise the request keeps running and causes the web application to wait for the shutdown timeout
5. The dashboard resource client detects the watch resources method call has failed and logs an error
6. The error is detected by the `DashboardLifecycleHook` who is watching for console output.
7. The error is printed to the app host console
8. As part of final shutdown of the app host the `DashboardLifecycleHook` is disposed which aborts watching for console output.

The PR makes the `DashboardLifecycleHook` stop watching for console output before step 4. It's no longer listening by the time the dashboard logs the error.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
