### PR TITLE
update subset of versions

### PR DESCRIPTION
**Pull request by danmoseley**
Update just versions that seem unlikely to be causing the failure in #3590 as a start at bisecting.

Note - the comments are merge helpers, really so that DCP updates don't conflict with the line below.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3610)

### CODE REVIEW

**Comment by danmoseley** [comment]
this is not hitting the issue in the larger PR (it's hitting the general test failure). so when that general issue is fixed, we can take this.

**Comment by eerhardt** [comment]
@radical  is going to disable this test. Someone deleted our azure resource and it broke our tests.

**Comment by radical** [comment]
> @radical is going to disable this test. Someone deleted our azure resource and it broke our tests.

Update: @ReubenBond restored the resources, and this should work now. I have triggered a rebuild.

**Comment by danmoseley** [comment]
@eerhardt can you sign off? then I can merge.

**Review by radical — APPROVED** [review]

**Pull request merged**
