### PR TITLE
Retry tests if msbuild crashes

### PR DESCRIPTION
**Pull request by radical**
And get the msbuild debug files from crashes to aid debugging.

Issue: https://github.com/dotnet/aspire/issues/6163

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6181)

### CODE REVIEW

**Comment by joperezr** [comment]
Do we understand why the crash is happening though? How confident are we that when in a failure state, retrying will make this pass?

**Comment by radical** [comment]
It doesn't crash like this on every build, but it does crash sometimes. So, this is just to ease the pain of having to do retries or having red builds on internal pipeline. Meanwhile, we are tracking the occurrence of these with https://github.com/dotnet/aspire/issues/6163 .

**Review by joperezr — APPROVED** [review]
LGTM, thanks @radical. If there is a way of not only retrying, but also keeping trace of when that needed to happen it would be great, as that way we won't get false-negatives indicating that this is no longer a problem, but that shouldn't block this.

**Comment by radical** [comment]
> LGTM, thanks @radical. If there is a way of not only retrying, but also keeping trace of when that needed to happen it would be great, as that way we won't get false-negatives indicating that this is no longer a problem, but that shouldn't block this.

I'm setting `MSBUILDDEBUGPATH` here, so we should get some debug logs from msbuild which we can use to further debug this.

**Pull request merged**
