### PR TITLE
Update a bunch of dependencies to latest

### PR DESCRIPTION
**Pull request by eerhardt**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2663)

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by radical** [comment]
`dependabot` is failing - https://github.com/dotnet/aspire/network/updates/796259011
Screenshot 2024-03-05 at 20 13 01

IIUC, it should have been able to run for the sdk-style project but it failed with `Property 'NetCurrent' was not found.`. This property is set by arcade. I hope it does a `restore` before trying to read the project file, though https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#nuget-cli suggests otherwise. (and [updater code](https://github.com/dependabot/dependabot-core/blob/6357b576ca6c5061d7423273dfd2489b58363c58/nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs#L26-L29)).

If that is correct then we would need to provide a default value for this property, matching the current value in Arcade. Restricting that value to be set only for dependabot run would be good.

cc @danmoseley - does that sound correct?

**Comment by eerhardt** [comment]
@radical - see https://github.com/dependabot/dependabot-core/issues/8490#issuecomment-1969386026

**Comment by danmoseley** [comment]
Maybe I should make a branch, with this directory.Packages.props, that is hacked enough that dependabot works in it, and we can periodically merge its changes back to main..

**Comment by radical** [comment]
You could try `<NetCurrent Condition="'$(ArcadeSdkVersion)' == ''">net8.0</NetCurrent>` which should be triggered when arcade is not restored, as that property is being set in arcade targets.
Or maybe even `$(ArcadeSdkBuildTasksAssembly) != ''`.

And we can add `and '$(ContiunuousIntegrationBuild)' != 'true'`, so it does not trigger on our CI.

If it works then it might be good enough for `main`.. maybe?

**Comment by radical** [comment]
ArcadeSdkVersion - https://github.com/dotnet/arcade/blob/f1ef2a8544824e9f4395f88e6b453d6fc2826d72/src/Microsoft.DotNet.Arcade.Sdk/Microsoft.DotNet.Arcade.Sdk.csproj#L67

**Pull request merged**
