### PR TITLE
Stay on the sync context when rendering console logs

### LINKED ISSUE #3458: Log streams not showing up
Seems like after #3343 the log streams are not responding and printing to the screen. 

https://github.com/dotnet/aspire/assets/4821/e0f8f872-5154-4473-b19d-47d49ea293ec

### PR DESCRIPTION
**Pull request by davidfowl**
- Don't use ConfigureAwait(false)

Fixes #3458
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3459)

### CODE REVIEW

**Review by ReubenBond — APPROVED** [review]

**Comment by JamesNK** [comment]
Can you make it ConfigureAwait(true) and/or have a comment that we need to stay on the sync context

**Comment by davidfowl** [comment]
ConfigureAwait(true) is jank, but I did it 😄

**Pull request merged**
