### PR TITLE
Add HTTPS test coverage for resource client/server integration tests

### PR DESCRIPTION
**Pull request by drewnoakes**
Contributes to #3739
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4621)

### CODE REVIEW

**Comment by drewnoakes** [comment]
Build seems to have timed out running `Aspire.Hosting.Tests`.

**Review by kvenkatrajan — APPROVED** [review]
Thanks!

**Pull request merged**
