### PR TITLE
Set correct AutoFocus value for FluentPopover

### LINKED ISSUE #3597: [AzureTools][Aspire] The opened "Endpoints" window flashes but does not disappear when clicking anywhere on the dashboard page again
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.10.0 Preview 3.0 [34809.128.d17.10]
**Aspire Version:** 8.0.0-preview.6.24210.22 
Apply NuGet Feeds

**REPRO STEPS:**

1. Create a Aspire starter Application project.
2. F5.
3. In the dashboard, click the numbers tab under the "Endpoints" -> An "Endpoints" window opens.
4. Click the numbers tab under the "Endpoints" again.

**Expect:**
The opened "Endpoints" window disappears.

**Actual:**
The opened "Endpoints" window flashes but does not disappear.
Actual

**More Info:**
1. The open "Endpoints" window disappears after refreshing the dashboard webpage.
2. The open "Endpoints" window stays open and flashes when you click anywhere on the dashboard page.
3. This issue doesn't reproduce on 17.10 Preview 3 with Aspire 8.0.0-preview.5.24201.12.

### PR DESCRIPTION
**Pull request by vnbaaij**
Fix #3597 The opened "Endpoints" window flashes but does not disappear when clicking anywhere on the dashboard page again
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3661)

### CODE REVIEW

**Review by kvenkatrajan — APPROVED** [review]

**Comment by eerhardt** [comment]
The bulid break is known. Fixing with https://github.com/dotnet/aspire/pull/3662. When that gets merged we can rerun CI here.

**Pull request merged**
