### PR TITLE
Add eventing to test builder.

### LINKED ISSUE #6681: Expose IDistributedApplicationEventing on IDistributedApplicationTestingBuilder
It's not possible to use the new eventing system from tests utilizing `IDistributedApplicationTestingBuilder` right now as the `IDistributedApplicationEventing` instance from the inner app host builder is not exposed.

### PR DESCRIPTION
**Pull request by mitchdenny**
## Description

We missed this. It was added to the test builder we use for our internal tests, but not the public API that we ship. Quick fix.

Fixes #6681 

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [ ] No
- Did you add public API?
  - [x] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [x] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [x] No (not required)
  - [ ] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6682)

### CODE REVIEW

**Comment by DamianEdwards** [comment]
@mitchdenny should we think about adding a test that verifies that members added to `DistributedApplicationBuilder` are exposed on the test builder? I imagine something that will fail whenever a new member is added that then requires either updating the test builder to expose it, or updating the test to explicitly confirm that we don't want to expose it.

**Comment by mitchdenny** [comment]
Or we could look at making the test builder derive?

**Comment by DamianEdwards** [comment]
Would be a bigger (breaking?) change to change inheritance wouldn't it? Open to it, just wondering if there's something more pragmatic for the shorter term.

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
> @mitchdenny should we think about adding a test that verifies that members added to `DistributedApplicationBuilder` are exposed on the test builder? I imagine something that will fail whenever a new member is added that then requires either updating the test builder to expose it, or updating the test to explicitly confirm that we don't want to expose it.

+1. Add a test with reflection over both. If the test builder is missing something from `DistributedApplicationBuilder` then throw an error unless in an allow list. New property on `DistributedApplicationBuilder` requires either adding it to test builder or adding it to allow list.

**Comment by DamianEdwards** [comment]
@mitchdenny are you planning to add a test as suggested, or log a follow-up issue?

**Comment by mitchdenny** [comment]
I'll add a test.

**Pull request merged**
