### PR TITLE
Add icon to MongoDB packages

### LINKED ISSUE #3928: Add icon to MongoDB hosting and component packages
We've received approval to use the following icon for the `Aspire.Hosting.MongoDB` and `Aspire.MongoDB.Driver` packages:

image

I have the original file appropriate for embedding in the packages.

### PR DESCRIPTION
**Pull request by DamianEdwards**
Fixes #3928
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3929)

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
LGTM

**Comment by eerhardt** [comment]
@DamianEdwards - is your plan to backport this to 8.0?

**Comment by DamianEdwards** [comment]
Yeah I guess we can.

**Pull request merged**
