### PR TITLE
Docker bound volume mounts resolve to OS local path

### PR DESCRIPTION
**Pull request by r0ss88**
Fix an issue when using docker context from WSL mounted path resolving as windows path (#993)

### CODE REVIEW

**Comment by r0ss88** [comment]
No, I had noticed that :)

**Comment by mitchdenny** [comment]
Testing this code is going to be a little awkward in terms of an end to end functional test - but perhaps it can be pulled out into an interna; helper method which we can call from Aspire.Hosting.Tests just to satisfy us that it covers all the various combinations that we could see.

**Comment by BrennanConroy** [comment]
Could you add a test like
https://github.com/dotnet/aspire/blob/07722afc66a940e10e0ba49ecd282e0fdf3584bc/tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs#L394
instead grabbing `Container` from `KubernetesService` and check the `Spec.VolumeMounts` property?

**Comment by BrennanConroy** [comment]
@r0ss88 are you still interested in updating this?

**Comment by r0ss88** [comment]
Apologies for the delayed response, I ended up working round this so no longer require this fix. I'd be happy to add the tests though to cover the change.

**Comment by r0ss88** [comment]
Hey @BrennanConroy, I have added the required unit tests as requested.

**Review by BrennanConroy — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Thank you @r0ss88 !

**Pull request merged**
