### PR TITLE
Cancel dashboard service streams on application shut down

### LINKED ISSUE #1557: Dashboard hangs when shutting down
This is what happens when running eshoplite and shutting down.

```
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'WatchResourceConsoleLogs'.
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.CancellationToken.ThrowIfCancellationRequested()
         at Grpc.AspNetCore.Server.Internal.HttpContextStreamWriter`1.WriteCoreAsync(TResponse message, CancellationToken cancellationToken)
         at Aspire.Hosting.Dashboard.DashboardService.WatchResourceConsoleLogs(WatchResourceConsoleLogsRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\dev\git\aspire\src\Aspire.Hosting\Dashboard\DashboardService.cs:line 110
         at Aspire.Hosting.Dashboard.DashboardService.WatchResourceConsoleLogs(WatchResourceConsoleLogsRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\dev\git\aspire\src\Aspire.Hosting\Dashboard\DashboardService.cs:line 101
         at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
         at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #1557

This prevents a delay during shutdown where we wait for connections to time out. Linking the `IHostApplicationLifetime.ApplicationStopping` cancellation token ensures these streams are closed immediately when application shut down is requested.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1633)

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
@davidfowl Have we ever considered an option in ASP.NET Core to raise the cancellation token of pending requests on application shutdown?

If we don't want Aspire shutdown to ever wait for requests to drain cleanly, we could centralize this behavior in middleware and replace the cancellation token on `HttpContext`.

**Comment by davidfowl** [comment]
> @davidfowl Have we ever considered an option in ASP.NET Core to raise the cancellation token of pending requests on application shutdown?

We haven't. The closest was kestrel's graceful shutdown support. I think there needs to be 2 tokens, one that signals the start of shutting down and the other the one that fires when the grace period is over. I also have an aversion to combining the per request token with the app shutdown token because of performance.

> If we don't want Aspire shutdown to ever wait for requests to drain cleanly, we could centralize this behavior in middleware and replace the cancellation token on HttpContext.

Sure but its only the streaming requests that would ever hang right?

**Comment by drewnoakes** [comment]
> I also have an aversion to combining the per request token with the app shutdown token because of performance.

In what sense? We link once per request, which is typically once on page load for resources, and once per request for console logs. Any overhead is tiny and infrequent as I understand it.

> I think there needs to be 2 tokens, one that signals the start of shutting down and the other the one that fires when the grace period is over.

We aren't doing anything with the gRPC service that requires graceful shutdown. We should just terminate the connection with the client as quickly as possible. Or am I missing something?

**Comment by davidfowl** [comment]
> In what sense? We link once per request, which is typically once on page load for resources, and once per request for console logs. Any overhead is tiny and infrequent as I understand it.

I mean in ASP.NET Core, not the dashboard app itself. This was in response to @JamesNK asking about doing it in ASP.NET Core itself.

**Comment by JamesNK** [comment]
> I also have an aversion to combining the per request token with the app shutdown token because of performance.

If we do application stopping cancellation inside ASP.NET Core then that wouldn't be necessary. We could listen to `ApplicationStopping` and then on cancellation look through outstanding requests and call `CancellationTokenSource.Cancel()` on pending HTTP requests. Per-request overhead would be zero.

SignalR does this already for its outstanding connections: https://github.com/dotnet/aspnetcore/blob/ef5f439ec8de63300097e666b6c10f3c13736576/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionManager.cs#L40

This could be a gRPC-level option, e.g. `RaiseCancellationOnStopping`. However, the internal CTS isn't available to gRPC so it would have to use a more inefficient `CancellationTokenSource.CreateLinkedTokenSource` to implement this.

**Comment by BrennanConroy** [comment]
FYI, people don't like how SignalR just closes connections on server shutdown. They want a chance to gracefully finish application code for any active connections before we ungracefully close them after some timeout.

**Comment by JamesNK** [comment]
I don't think ASP.NET Core should abort connections on stopping, just raise the cancellation token. But HttpContext's cancellation token is called `HttpContext.RequestAborted` and it would be odd to raise the aborted token when the request isn't aborted.

Yeah, adding this as an ASP.NET Core feature doesn't have a simple clean solutation.

I'll consider the scenario in gRPC. A new option, or just documentation? TBD. Issue: https://github.com/grpc/grpc-dotnet/issues/2357

**Pull request merged**
