### PR TITLE
Make KeyVault parent explicit.

### PR DESCRIPTION
**Pull request by mitchdenny**
Minor change to make keyvault parent more explicit in the PublishAsAzureKeyvaultFlexibleServerInternal method.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3276)

### CODE REVIEW

**Comment by davidfowl** [comment]
Is this the only one?

**Comment by mitchdenny** [comment]
> Is this the only one?

Cosmos is another one. Updated in this PR too.

**Review by davidfowl — APPROVED** [review]

**Comment by davidfowl** [comment]
@mitchdenny I don't think this is preview 5

**Comment by mitchdenny** [comment]
Its not blocking.

**Pull request merged**
