### PR TITLE
Remove commas between endpoints in grid

### PR DESCRIPTION
**Pull request by drewnoakes**
## Description

The commas between endpoints are redundant as the underline of the anchor visually separates multiple entries. The comma visually collides with the underline, and looks a bit strange when there's only one item and the rest in overflow.

Subjective, but I think it looks a little sharper like this.

### Before

image

image

### After

image

image

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6359)

### CODE REVIEW

**Comment by JamesNK** [comment]
> The commas between endpoints are redundant as the underline of the anchor visually separates multiple entries.

This won't be true for tcp endpoints. They're plain text.

However, maybe the space can be the delimiter. That shouldn't be a situation where an endpoint contains spaces.

**Comment by drewnoakes** [comment]
> This won't be true for tcp endpoints. They're plain text.

True, some URLs won't be hyperlinked or underlined, but the space should still be clear.

**Comment by DamianEdwards** [comment]
Yeah I like this change

**Review by adamint — APPROVED** [review]
Agree that space is an acceptable delimiter here

**Comment by drewnoakes** [comment]
@adamint the test failure here seems related to health checks. Did we commit something that breaks tests?

```
Assert.Null() Failure: Value of type 'Nullable<HealthStatus>' has a value
Expected: null
Actual:   Healthy
```

**Pull request merged**
