### PR TITLE
Fix Azurite support

### LINKED ISSUE #4288: Azurite broken with API version mismatch
```
The API version 2024-05-04 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 
```

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #4288

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4279)

### CODE REVIEW

**Comment by sebastienros** [comment]
Will add the tests and refactor the tags after the WE if it hasn't been merged. Azurite won't work on `main` without it.

**Review by davidfowl — APPROVED** [review]

**Comment by rob-king-volpara** [comment]
In case anyone lands here and is blocked by this in the meantime, you can update to the newer image with:

```
IResourceBuilder<AzureStorageResource> storage = builder.AddAzureStorage("Storage");
if (builder.Environment.IsDevelopment())
{
    storage.RunAsEmulator().WithAnnotation(new ContainerImageAnnotation
    {
        Registry = "mcr.microsoft.com",
        Image = "azure-storage/azurite",
        Tag = "3.30.0"
    });
}

**Comment by davidfowl** [comment]
@rob-king-volpara You can do:

```C#
builder.AddAzureStorage("storage")
       .RunAsEmulator(c => c.WithImageTag("3.30.0"));
```

**Comment by rob-king-volpara** [comment]
Yeah I did consider that, but does that mean it would try to use the emulator if I published it to Azure with "azd"?

**Comment by davidfowl** [comment]
@rob-king-volpara no RunAs* means only affect the resource in "RunMode".

**Pull request merged**
