### PR TITLE
Enable template localization for Aspire templates

### LINKED ISSUE #1996: Localization of templates

### LINKED ISSUE #2722: [WebToolsE2E][Aspire] Some contents in the Aspire template are not localized in CHS OS.
**REGRESSION INFO:** Repro on Dev17.10 Preview 1 (Includes Aspire 8.0.0-preview.3.24105.21)

**TESTCASES AFFECTED**
Aspire Templates

**INSTALL STEPS**

1. Clean machine: Win11 x64 22h2 CHS
2. Install 17.10.0 Preview 2.0 [34629.198.main] (Includes Aspire 8.0.0-preview.4.24128.4)
3. Apply NuGet Feeds

**REPRO STEPS**
1. Open VS > click "Create new project" > Type "Aspire" in the search bar.

**ACTUAL:**

The project template is not localized.

image

Select '.NET Aspire Starter Application' > Next

image

**EXPECTATION:**
Aspire Templates should be localized in CHS OS.

### PR DESCRIPTION
**Pull request by joperezr**
Fixes #1996
Fixes #2722 

This change will enable template localization for Aspire templates.

# Summary

- Adds `<UsingToolTemplateLocalizer>true</>` to projects containing templates.
- Generates localization files to be translated by loc team

# What to expect after merging

- The dev making the change should build (at the very least) the modified template project. This will update the loc files on the local working copy,
- Push the loc files together with the template modifications. Review & merge.
- OneLocBuild integration will automatically pick up the changes and will send them for translation.
- You will receive a PR containing the translated template loc files when they are ready. Review & merge.

cc: @DamianEdwards @kvenkatrajan 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2858)

### CODE REVIEW

**Review by DamianEdwards — APPROVED** [review]
Looks good!

**Comment by KirillOsenkov** [comment]
@joperezr Should we be localizing the templates that we copy to obj? Right now it seems that it is localizing the sources, not the obj. Is this by design?

**Comment by joperezr** [comment]
> @joperezr Should we be localizing the templates that we copy to obj? Right now it seems that it is localizing the sources, not the obj. Is this by design?

mmm perhaps I'm missing something, but I thought in here we are configuring so that these files get generated for the inputs and then those get analyzed by the loc team and fix those. Can you share more what your concern is here?

**Comment by danmoseley** [comment]
I'd have expected we'd have gotten bugs if they weren't localized correctly over the last year...

**Comment by KirillOsenkov** [comment]
Yes, no concern, I didn't even look too closely, just noticed the template path is to the project root, not the obj, but maybe it's supposed to be like this. Feel free to just ignore this.

**Pull request merged**
