### PR TITLE
Make status column icons colorblind friendly

### PR DESCRIPTION
**Pull request by drewnoakes**
Ensures these icons are differentiated not only by colour, but also by icon.

Also fixes this issue, pointed out offline by @timheuer:

image

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3401)

### CODE REVIEW

**Review by mitchdenny — APPROVED** [review]

**Review by tlmii — APPROVED** [review]

**Review by timheuer — APPROVED** [review]

**Review by adamint — APPROVED** [review]

**Comment by danmoseley** [comment]
do any of the 3 remaining uses of ""Icons.Filled.Size16.Circle"" in that file need to be visually distinguishable?

**Comment by drewnoakes** [comment]
I think the featureless circle makes sense for "unknown" state, which is two of the three. The other is "starting" state. Perhaps that could be an outlined circle.

**Comment by drewnoakes** [comment]
Did we ever consider using a spinner for "starting" status items?

https://blazorfluentui.azurewebsites.net/spinnerPage

**Comment by danmoseley** [comment]
Looks appropriate to me, my 2c

**Comment by danmoseley** [comment]
> The other is "starting" state. Perhaps that could be an outlined circle.

@drewnoakes do we still need to distinguish this, to be accessible?

**Comment by drewnoakes** [comment]
> @drewnoakes do we still need to distinguish this, to be accessible?

Yes, https://github.com/dotnet/aspire/pull/3689

I decided against using a spinner, mostly because it didn't seem possible to make the Blazor Fluent UI one that small.

**Pull request merged**
