### PR TITLE
#3986 Rename of yarp package to clarify functionality

### LINKED ISSUE #3986: Reworking of Microsoft.Extensions.ServiceDiscoveery packages
Currently there is 2 quite different use cases achieved by the Microsoft.Extensions.ServiceDiscoveery.* packages and to clear things up packages should be split renamed before GA release.

The final structure invisioned is as follows:
-

### PR DESCRIPTION
**Pull request by thompson-tomo**
Move yarp to be under service resolution naming rather than service discovery as it is not actually using yarp for service discovery.

closes #3986 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3992)

### CODE REVIEW

**Comment by danmoseley** [comment]
@ReubenBond  thoughts? This is breaking, right?

**Comment by thompson-tomo** [comment]
yes @danmoseley it would be breaking due to namespace & package name change but prior to GA is the best time to do this.

Key thing for me is yarp is not actually being used for ServiceDiscovery with this package.

**Comment by davidfowl** [comment]
Yes, its unlikely we'll take this PR as this code already went through API review.

**Comment by danmoseley** [comment]
Cc @mitchdenny 

Yeah GA branch is now ship stoppers only pretty much. I think this just came too late.

**Comment by thompson-tomo** [comment]
If it is too late perhaps we split this in 2:

- Rename package as 1 PR for GA branch but leave namespace
- In v9 we update the namespace to match the package

This would make the change easier for users if we don't want to change both package and namespace for intial GA (my preference).

**Comment by davidfowl** [comment]
It's too late and I don't know why we'd make this change at all.

**Comment by thompson-tomo** [comment]
Let me phrase it another way, when a user installs a service discovery package the clear expectation is that the provider named ie YARP is the source where services are discovered from. This is how the DNS package works. The yarp package implements a different interface to the DNS package and is actually simply resolving the urls for the destinations specified in the yarp config.

**Comment by davidfowl** [comment]
That doesn’t change what I said. There was an APi review process that was followed. Thats the process you go through again with your valid feedback and the committee decide. This PR and the associated issues doesn’t follow any of the process.

**Comment by danmoseley** [comment]
I'm closing this PR for discussion to occur in the issue.

**Pull request closed without merging**
