### PR TITLE
[8.0-preview2] Show proxy URL for all executables

### LINKED ISSUE #1335: Dashboard is showing endpoint URL for application instead of the proxy
In preview.2 builds, the dashboard is showing the endpoint URL of the application executable instead of the URL of the proxy in front of it. The proxy is the one getting the port specified in the case of a project with a launch profile, so the user gets directed to the URL that doesn't match what the project specifies.

### PR DESCRIPTION
**Pull request by smitpatel**
For multiple replica, replica endpoint will be shown in bracket

Fixes #1335

image

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1344)

### CODE REVIEW

**Review by DamianEdwards — APPROVED** [review]
I checked out the branch locally and verified the proxy URLs for no-replica & replica projects worked, as well as the instance URLs for replicas.

**Review by davidfowl — APPROVED** [review]

**Comment by eerhardt** [comment]
@smitpatel - did this change also make it into `main`? If not, it will be lost in the next preview.

**Comment by joperezr** [comment]
> @smitpatel Smit Patel FTE - did this change also make it into `main`? If not, it will be lost in the next preview.

We actually do a merge back from release branches to main once we release in order to not miss things

**Comment by smitpatel** [comment]
@eerhardt @joperezr - This change is not in main. What should I do here process wise?
- Submit similar fix PR to main branch?
- Submit PR to merge release to main branch? (Would some other mechanism do it?)

**Pull request merged**
