### PR TITLE
DcpDependencyCheck: throw instead of crashing process

### LINKED ISSUE #2928: Throw instead of calling `Environment.Exit` in `DcpDependencyCheck`
If the cancellation token passed to `DcpDependencyCheck.EnsureDcpDependenciesAsync(...)` is canceled before completion, this will currently crash the process. Instead, it should clean up and propagate the cancellation up the stack.

This is causing testing to crash when the test builder is not used as intended. We should not terminate the process this way, or we should provide a way to opt-out of crashing the process. There are 4 `Environment.Exit` calls in `DcpDependencyCheck`. They should all be converted into exceptions which propagate up the stack. This would improve the debugging experience.

Are the error codes passed to `Environment.Exit` important?

### PR DESCRIPTION
**Pull request by ReubenBond**
Fixes #2928
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2931)

### CODE REVIEW

**Comment by danegsta** [comment]
We return those particular error codes to allow IDEs to tell if Aspire failed due to a missing container runtime requirements (they currently drive warnings in VS, for example).

**Comment by ReubenBond** [comment]
Do the IDEs do this currently? The issue with Environment.Exit is that it cannot be intercepted and a developer just sees a crash, maybe with an error code.
Currently, it crashes on cancellation, not just on actual dependency issues. Cancellation is normal/expected.

**Comment by davidfowl** [comment]
This should throw an exception and then have it fail with the specific exit code when running from the IDE.

**Comment by ReubenBond** [comment]
> This should throw an exception and then have it fail with the specific exit code when running from the IDE. Using the env var.

Is this something I can do in this PR? What do I search for? I'm not aware of an env var

**Comment by danegsta** [comment]
We could have VS set an environment variable when running F5/CTRL+F5; alternatively, we could add the ability to apply an exit code/reason to the exception and use a last chance exception handler to exit with the appropriate code if found.

**Comment by davidfowl** [comment]
Lets close on the approach tomorrow. I also need to change this code so that the container runtime makes it all the way out of the dependency check so it can be used later.

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/aspire/pull/3026.

**Pull request closed without merging**
