### PR TITLE
Bump Polly to 8.4.1

### PR DESCRIPTION
**Pull request by martincostello**
- Bump Polly to [8.4.1](https://github.com/App-vNext/Polly/releases/tag/8.4.1) to pick up bug fixes:
  - https://github.com/App-vNext/Polly/pull/2164
  - https://github.com/App-vNext/Polly/pull/2166
- Group Polly dependabot updates to avoid multiple PRs such as:
  - #4167
  - #4200

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4745)

### CODE REVIEW

**Comment by martincostello** [comment]
I think the packages need mirroring.

**Comment by danmoseley** [comment]
I thought I did.. I'll try again

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
I had mirrored Polly but not Polly.Extensions.

We really need an the internal mirror process to be easier, it makes me type in every package and version number, each one is a pipeline run unless I just want latest .. maybe @joperezr already has a script...

**Comment by danmoseley** [comment]
for this reason, I'm inclined to mostly ignore random updates eg AWS patch versions and then catch up for our releases. whereas this Polly update, it's clear it brings improvements we need.

**Comment by joperezr** [comment]
> I had mirrored Polly but not Polly.Extensions.
> 
> 
> 
> We really need an the internal mirror process to be easier, it makes me type in every package and version number, each one is a pipeline run unless I just want latest .. maybe @joperezr already has a script...

Technically speaking, you can likely get away with a single run most of the time if you keep version as "latest". Given the whole point of these updates is to mirror latest on NuGet, having "latest" on the pipeline means "latest for each package available on NuGet" which is most of the time what you want with these updates. That said, I think it is great feedback, and we should ask @dotnet/dnceng to see if they can allow passing in key-value pairs instead.

**Comment by danmoseley** [comment]
cc @radical fyi ^^

**Comment by danmoseley** [comment]
Looks like it takes 46 mins to do the whole lot.

**Pull request merged**
