### PR TITLE
Change Aspire URLs so trace detail is selected

### LINKED ISSUE #2357: [AzureTools][Aspire] Icon “Traces” isn't selected and highlighted after clicking a link under the "Trace" tab of "Structured"
**Clean machine**: Win11 x64 23h2 ENU
**VS Version:** VS 17.10 Preview 2 from [34618.16.main]
**Aspire Version:** 8.0.0-preview.4.24118.7
Apply NuGet Feeds

**REPRO STEPS:**

1. Create a Aspire starter project with "Use Redis for caching (requires Docker) checked.
2. F5
3. In the dashboard, click "Structured" -> Click any link under the "Trace" tab.
    image

**Expect:** 
Icon “Traces” is selected and highlighted. 
image

**Actual:** 
Icon “Traces” isn't selected and highlighted. 
image

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspire/issues/2357

The menu bar highlights items based on the URL. The start of URL path needs to match the item URL.

This PR changes URLs. The most notable change is the resource name in the URL follows a `/Resource/` segment:
* Before: `/ConsoleLogs/xxx`, After: `/ConsoleLogs/Resource/xxx`
* Before: `/Traces/xxx`, After: `/Traces/Resource/xxx`
* Before: `/Trace/xxx`, After: `/Traces/Detail/xxx` <- problem URL. New URL starts with `/Traces` so the menu bar is highlighted.

After:
image

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2368)

### CODE REVIEW

**Comment by JamesNK** [comment]
cc @davidfowl @DamianEdwards in case you have strong opinions about URLs.

**Comment by davidfowl** [comment]
They should be lowercase

**Comment by JamesNK** [comment]
Do you want ALL literal URLs lowercase? I wouldn't mind doing that. Mix case URLs are kind of ugly.

**Comment by davidfowl** [comment]
Yep they should all be lowercase

**Review by tlmii — APPROVED** [review]
Not positive I like the addition of /resource/ in many places (seems superfluous) but when looking at the set of URLs as a whole, there's some consistency there, so I'm fine with it. Other changes make sense for sure.

**Comment by JamesNK** [comment]
> Not positive I like the addition of /resource/ in many places (seems superfluous)

I'm not a huge fan either, but without it any URLs that start with those prefixes could conflict with a resource name. e.g. `/traces/detail/123` could conflict with a resource called `detail`.

**Pull request merged**
