### PR TITLE
Add console logs button to main grid

### LINKED ISSUE #5975: Make view logs a top level command
Logs are too important to be 2 clicks. We should make it a top level command again.

cc @JamesNK

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

I made a bunch of changes to make this look good:

* Add console logs action button to main grid
* Now up to one command can be highlighted (first in order). If there is no highlighted command then a spacer is added for consistent width
* Add tooltip to actions button
* Top-level actions are all hidden in mobile view. Just actions menu button is visible

Fixes https://github.com/dotnet/aspire/issues/5975

image

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6011)

### CODE REVIEW

**Comment by drewnoakes** [comment]
I find the separator makes it look like there's two columns in there.

It also feels like the ... icon should be the last in the list.

How about instead of:

image

We have:

image

**Comment by JamesNK** [comment]
Having it feel slightly separate was intentional to separate commands (and the button to show more commands) from console logs. And two icons + separator + icon feels a bit less overwhelming than three icons together.

I don't have a strong opinion. @davidfowl @leslierichardson95 Do you have any preference?

**Comment by drewnoakes** [comment]
Tangentially related to this PR, but if we're going to use this console icon more prominently, perhaps we also add it here, instead of text:

image

**Comment by davidfowl** [comment]
It’s subtle but I like @drewnoakes’s suggestion to put it next to stop.

**Comment by JamesNK** [comment]
Swapped buttons. I kept the divider. IMO it looks better with a divider.

3 icons together multipled by many rows feels like too many icons. I think the divider gives some structured (buttons you can click immediately vs more menu button) and is less overwhelming.

With divider:
image

Without divider:
image

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
