### PR TITLE
Throw from `GetEndpoint` if the service binding does not exist

### LINKED ISSUE #609: Make GetEndpoint throw if there's no sevice binding with that name
Today GetEndpoint just returns an EndpointReference even if there is no service binding. Instead it should throw an exception.

### PR DESCRIPTION
**Pull request by chrisdcmoore**
Fixes #609

### CODE REVIEW

**Comment by davidfowl** [comment]
Can you add a unit test?

**Comment by chrisdcmoore** [comment]
Done in 370864ed864472b8736d31cb8b7e92f5e104daf4 - wasn't quite sure where they should live so chose `WithServiceBindingTests` as the best candidate - LMK if they should be moved

**Comment by chrisdcmoore** [comment]
The eShop sample fails to start with this change 🤦 Possibly I've confused `AllocatedEndpointAnnotation` with `ServiceBindingAnnotation`? Converted to draft for now...

**Comment by davidfowl** [comment]
I think it's because this binding gets added later in the pipeline.

**Comment by davidfowl** [comment]
I guess we have to defer this throwing until way later in the flow.

**Comment by mitchdenny** [comment]
Are you still interested in this PR @chrisdcmoore? There have been a few changes around method names, but I still thing this PR has value!

**Comment by chrisdcmoore** [comment]
My apologies, I haven't had the time to dedicate getting the Aspire pipeline into my head at the moment - I think it's probably better to close this off so someone else can pick it up (even if that's me at a later date). Sorry for the time lost reviewing this folks!

**Pull request closed without merging**
