### PR TITLE
Add IResourceWithServiceDiscovery interface to PythonProjectResource.

### LINKED ISSUE #5019: [8.1] using WithReference() with a python app fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When adding a python app as a reference to another project type (in this case Npm), it fails with 
image

(it can't figure out PythonProjectResource is just IResourcewithConnectionString)

### Expected Behavior

I should be able to reference python projects just like the rest of them 🤪

### Steps To Reproduce

```
var builder = DistributedApplication.CreateBuilder(args);

var py = builder.AddPythonProject("python-app", "../python-app/", "myteam.py")
    .WithHttpEndpoint(env: "FLASK_RUN_PORT");

var node = builder.AddNpmApp("frontend", "../node-app", "watch")
    .WithHttpEndpoint(env: "PORT")
    .WithReference(py);

builder.Build().Run();
 
```

When you run it'll fail!

### Exceptions (if any)

_No response_

### .NET Version info

 dotnet --info
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.d7126b9e
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.301/

.NET workloads installed:
 [maui-tizen]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [maui-maccatalyst]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [maui-ios]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [maui-android]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.1.0/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.6
  Architecture: arm64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]
  8.0.301 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

### Anything else?

VS Code!

### PR DESCRIPTION
**Pull request by mitchdenny**
Fixes #5019 

We were just missing the marker interface. This will result in the service discovery variables be populated with `WithRefrence(...)` is used. It also unlocks `WithEnvironment(string, EndpointReference)` which is arguably more useful in these polyglot scenarios.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5024)

### CODE REVIEW

**Review by maddymontaquila — APPROVED** [review]
love it thank you!!!

**Review by IEvangelist — APPROVED** [review]

**Comment by eerhardt** [comment]
Are there any tests we could write to ensure this works end-to-end?

**Pull request merged**
