### PR TITLE
[tests] Run SqlServer, and PostgreSQL tests on helix

### PR DESCRIPTION
**Pull request by radical**
Related: https://github.com/dotnet/aspire/issues/1167
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2162)

### CODE REVIEW

**Review by eerhardt — COMMENTED** [review]
Can we remove this now?

https://github.com/dotnet/aspire/blob/32d32abb43db470e4224585d1171da162c197042/tests/Aspire.Dashboard.Tests/Aspire.Dashboard.Tests.csproj#L6-L7

**Comment by radical** [comment]
Some tests are being skipped ([log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-heads-aj-more-helix-tests-d1bd72acca0d41cfb8/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests/1/console.569194ff.log?helixlogtype=result):
```
[xUnit.net 00:00:01.57]     Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.ConformanceTests_Pooling_TypeSpecificConfig.TracingEnablesTheRightActivitySource [SKIP]
[xUnit.net 00:00:01.57]       Unable to connect to the server.
```

Are the tests assuming already running sqlserver to be available? Can we use docker to make these available on helix, like just the specific server needed for the tests?

**Comment by eerhardt** [comment]
> Are the tests assuming already running sqlserver to be available? Can we use docker to make these available on helix, like just the specific server needed for the tests?

Yes, all the components tests run in "2 modes".

1. If they can detect a local sqlserver running, it runs all the tests using that local server.
2. If the detection fails, any tests that need to actually connect to a sqlserver are skipped. Only the tests that don't need the connection are executed.

I'm currently trying out https://dotnet.testcontainers.org/ to make this better. That way the full suite of tests can be run locally or CI, without having to set up a local sqlserver. (Note: I've started with Redis and RabbitMQ, but the same idea should work for others.)

**Review by eerhardt — APPROVED** [review]
Awesome! Thanks

**Pull request merged**
