### PR TITLE
Retry on YamlException when loading Kubernetes client configuration

### PR DESCRIPTION
**Pull request by ReubenBond**
I encountered this while running an integration test:
image

My assumption is that this is caused by a race between writing and ready the Kubernetes client configuration file. By handling the resulting `YamlException`, we allow the process to be retried.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/3229)

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]
Add a comment

**Comment by ReubenBond** [comment]
Done: 
```csharp
// Handle exceptions caused by races between writing and reading the configuration file.
// If the file is loaded while it is still being written, this can result in a YamlException being thrown.
ShouldHandle = new PredicateBuilder().Handle<KubeConfigException>().Handle<YamlException>(),
```

**Comment by davidfowl** [comment]
@joperezr why does the bot not like @ReubenBond ?

**Pull request merged**
