### PR TITLE
Made translations more consistent with template rename for English locale

### PR DESCRIPTION
**Pull request by thimok**
Made translations for Aspire-Starter and Aspire-Empty templates more in line with the recent English change.

Reference issue: #4495 
Relevant commit for English change: https://github.com/dotnet/aspire/commit/90cd4b58a78379650a584b297e4328fdd5319bb6

Note: as I don't speak the languages, I have tried to translate them as accurately as possible with using a translation engine. Feel free to point issues out in a review.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4514)

### CODE REVIEW

**Comment by thimok** [comment]
@dotnet-policy-service agree

**Comment by sebastienros** [comment]
NB: In the ASP.NET repository, the name we use is `ASP.NET (Empty)`, it might be easier to translate -> `ASP.NET Core (空)`

**Comment by thimok** [comment]
> NB: In the ASP.NET repository, the name we use is `ASP.NET Core (Empty)`, it might be easier to translate -> `ASP.NET Core (空)`

I didn't want to change the structure of the translations in this PR. My goal was to make them consistent with the English locale as much as I was able to.

**Comment by adamint** [comment]
@joperezr could we get these localized by our vendors?

**Comment by joperezr** [comment]
> @joperezr could we get these localized by our vendors?

These are already being localized by our vendors, but I think that they have been having some issues in the process lately.

**Comment by danmoseley** [comment]
Thanks @thimok . I'm not sure, though, whether the localization process gets confused if we localize directly there. If nothing else, it will potentially get wiped out in the next update from their database.

@kvenkatrajan do we have someone in the loc team that we can @-mention here to answer this question?

**Comment by danmoseley** [comment]
@thimok I merged a number of loc string updates yesterday. Could you please rebase and see whether there's anything important remaining?

For those, I will have to open loc issues. Note, we do that for strings that are clearly wrong (or not localized at all) and generally not for little tweaks, although I could try. (Because prioritization of loc resources). I can't speak most of these languages, so I'd rely on folks that can to say "no this translation is just wrong"...

**Comment by danmoseley** [comment]
@thimok I'm going to close given many of these were updated. Please reopen this PR or a new one if rebased changes still are needed.

**Pull request closed without merging**
